<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Accounting.Domain\Accounting.Domain.csproj" />
    <ProjectReference Include="..\..\Core\Accounting.Application\Accounting.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Accounting.Infrastructure.Persistence\Accounting.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Accounting.Infrastructure.Compliance\Accounting.Infrastructure.Compliance.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
