<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="HSoThueDTu">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="HSoKhaiThue">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="TTinChung">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="PBanTKhaiXML" type="xs:string"/>
                    <xs:element name="MaTKhai" type="xs:string"/>
                    <xs:element name="TenTKhai" type="xs:string"/>
                    <xs:element name="KyKhaiThue" type="xs:string"/>
                    <xs:element name="MST" type="xs:string"/>
                    <xs:element name="TenNNT" type="xs:string"/>
                    <xs:element name="NguoiKy" type="xs:string"/>
                    <xs:element name="NgayKy" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="CTietTKhaiChinh">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ThueDauVao" type="xs:decimal"/>
                    <xs:element name="ThueDauRa" type="xs:decimal"/>
                    <xs:element name="ThuePhaiNop" type="xs:decimal"/>
                    <xs:element name="ThueConDuocKhauTru" type="xs:decimal"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
