// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bank.sql

package mariadb

import (
	"context"
	"database/sql"
)

const createBankTransaction = `-- name: CreateBankTransaction :exec
INSERT INTO bank_transactions (
    id,
    voucher_id,
    company_profile_id,
    bank_account_id,
    transaction_type,
    counterparty_account_no,
    counterparty_bank_name,
    counterparty_name,
    bank_reference_no,
    fee_amount_vnd,
    vat_fee_amount_vnd,
    total_amount_vnd
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateBankTransactionParams struct {
	ID                    string                          `json:"id"`
	VoucherID             string                          `json:"voucher_id"`
	CompanyProfileID      string                          `json:"company_profile_id"`
	BankAccountID         string                          `json:"bank_account_id"`
	TransactionType       BankTransactionsTransactionType `json:"transaction_type"`
	CounterpartyAccountNo sql.NullString                  `json:"counterparty_account_no"`
	CounterpartyBankName  sql.NullString                  `json:"counterparty_bank_name"`
	CounterpartyName      sql.NullString                  `json:"counterparty_name"`
	BankReferenceNo       sql.NullString                  `json:"bank_reference_no"`
	FeeAmountVnd          string                          `json:"fee_amount_vnd"`
	VatFeeAmountVnd       string                          `json:"vat_fee_amount_vnd"`
	TotalAmountVnd        string                          `json:"total_amount_vnd"`
}

func (q *Queries) CreateBankTransaction(ctx context.Context, arg CreateBankTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createBankTransaction,
		arg.ID,
		arg.VoucherID,
		arg.CompanyProfileID,
		arg.BankAccountID,
		arg.TransactionType,
		arg.CounterpartyAccountNo,
		arg.CounterpartyBankName,
		arg.CounterpartyName,
		arg.BankReferenceNo,
		arg.FeeAmountVnd,
		arg.VatFeeAmountVnd,
		arg.TotalAmountVnd,
	)
	return err
}

const getBankTransactionByID = `-- name: GetBankTransactionByID :one
SELECT 
    id,
    voucher_id,
    company_profile_id,
    bank_account_id,
    transaction_type,
    counterparty_account_no,
    counterparty_bank_name,
    counterparty_name,
    bank_reference_no,
    fee_amount_vnd,
    vat_fee_amount_vnd,
    total_amount_vnd
FROM bank_transactions
WHERE id = ?
`

func (q *Queries) GetBankTransactionByID(ctx context.Context, id string) (BankTransaction, error) {
	row := q.db.QueryRowContext(ctx, getBankTransactionByID, id)
	var i BankTransaction
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.CompanyProfileID,
		&i.BankAccountID,
		&i.TransactionType,
		&i.CounterpartyAccountNo,
		&i.CounterpartyBankName,
		&i.CounterpartyName,
		&i.BankReferenceNo,
		&i.FeeAmountVnd,
		&i.VatFeeAmountVnd,
		&i.TotalAmountVnd,
	)
	return i, err
}

const getBankTransactionByVoucherID = `-- name: GetBankTransactionByVoucherID :one
SELECT 
    id,
    voucher_id,
    company_profile_id,
    bank_account_id,
    transaction_type,
    counterparty_account_no,
    counterparty_bank_name,
    counterparty_name,
    bank_reference_no,
    fee_amount_vnd,
    vat_fee_amount_vnd,
    total_amount_vnd
FROM bank_transactions
WHERE voucher_id = ?
`

func (q *Queries) GetBankTransactionByVoucherID(ctx context.Context, voucherID string) (BankTransaction, error) {
	row := q.db.QueryRowContext(ctx, getBankTransactionByVoucherID, voucherID)
	var i BankTransaction
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.CompanyProfileID,
		&i.BankAccountID,
		&i.TransactionType,
		&i.CounterpartyAccountNo,
		&i.CounterpartyBankName,
		&i.CounterpartyName,
		&i.BankReferenceNo,
		&i.FeeAmountVnd,
		&i.VatFeeAmountVnd,
		&i.TotalAmountVnd,
	)
	return i, err
}
