// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cash.sql

package mariadb

import (
	"context"
	"database/sql"
)

const createCashPayment = `-- name: CreateCashPayment :exec
INSERT INTO cash_payments (
    id,
    voucher_id,
    company_profile_id,
    receiver_name,
    receiver_address,
    reason,
    cash_account_id,
    total_amount_vnd,
    is_non_cash_override,
    override_reason,
    accompanying_documents
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateCashPaymentParams struct {
	ID                    string         `json:"id"`
	VoucherID             string         `json:"voucher_id"`
	CompanyProfileID      string         `json:"company_profile_id"`
	ReceiverName          string         `json:"receiver_name"`
	ReceiverAddress       sql.NullString `json:"receiver_address"`
	Reason                string         `json:"reason"`
	CashAccountID         string         `json:"cash_account_id"`
	TotalAmountVnd        string         `json:"total_amount_vnd"`
	IsNonCashOverride     bool           `json:"is_non_cash_override"`
	OverrideReason        sql.NullString `json:"override_reason"`
	AccompanyingDocuments sql.NullString `json:"accompanying_documents"`
}

func (q *Queries) CreateCashPayment(ctx context.Context, arg CreateCashPaymentParams) error {
	_, err := q.db.ExecContext(ctx, createCashPayment,
		arg.ID,
		arg.VoucherID,
		arg.CompanyProfileID,
		arg.ReceiverName,
		arg.ReceiverAddress,
		arg.Reason,
		arg.CashAccountID,
		arg.TotalAmountVnd,
		arg.IsNonCashOverride,
		arg.OverrideReason,
		arg.AccompanyingDocuments,
	)
	return err
}

const createCashReceipt = `-- name: CreateCashReceipt :exec
INSERT INTO cash_receipts (
    id,
    voucher_id,
    company_profile_id,
    payer_name,
    payer_address,
    reason,
    cash_account_id,
    total_amount_vnd,
    accompanying_documents
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateCashReceiptParams struct {
	ID                    string         `json:"id"`
	VoucherID             string         `json:"voucher_id"`
	CompanyProfileID      string         `json:"company_profile_id"`
	PayerName             string         `json:"payer_name"`
	PayerAddress          sql.NullString `json:"payer_address"`
	Reason                string         `json:"reason"`
	CashAccountID         string         `json:"cash_account_id"`
	TotalAmountVnd        string         `json:"total_amount_vnd"`
	AccompanyingDocuments sql.NullString `json:"accompanying_documents"`
}

func (q *Queries) CreateCashReceipt(ctx context.Context, arg CreateCashReceiptParams) error {
	_, err := q.db.ExecContext(ctx, createCashReceipt,
		arg.ID,
		arg.VoucherID,
		arg.CompanyProfileID,
		arg.PayerName,
		arg.PayerAddress,
		arg.Reason,
		arg.CashAccountID,
		arg.TotalAmountVnd,
		arg.AccompanyingDocuments,
	)
	return err
}

const getCashPaymentByID = `-- name: GetCashPaymentByID :one
SELECT 
    id,
    voucher_id,
    company_profile_id,
    receiver_name,
    receiver_address,
    reason,
    cash_account_id,
    total_amount_vnd,
    is_non_cash_override,
    override_reason,
    accompanying_documents
FROM cash_payments
WHERE id = ?
`

func (q *Queries) GetCashPaymentByID(ctx context.Context, id string) (CashPayment, error) {
	row := q.db.QueryRowContext(ctx, getCashPaymentByID, id)
	var i CashPayment
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.CompanyProfileID,
		&i.ReceiverName,
		&i.ReceiverAddress,
		&i.Reason,
		&i.CashAccountID,
		&i.TotalAmountVnd,
		&i.IsNonCashOverride,
		&i.OverrideReason,
		&i.AccompanyingDocuments,
	)
	return i, err
}

const getCashPaymentByVoucherID = `-- name: GetCashPaymentByVoucherID :one
SELECT 
    id,
    voucher_id,
    company_profile_id,
    receiver_name,
    receiver_address,
    reason,
    cash_account_id,
    total_amount_vnd,
    is_non_cash_override,
    override_reason,
    accompanying_documents
FROM cash_payments
WHERE voucher_id = ?
`

func (q *Queries) GetCashPaymentByVoucherID(ctx context.Context, voucherID string) (CashPayment, error) {
	row := q.db.QueryRowContext(ctx, getCashPaymentByVoucherID, voucherID)
	var i CashPayment
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.CompanyProfileID,
		&i.ReceiverName,
		&i.ReceiverAddress,
		&i.Reason,
		&i.CashAccountID,
		&i.TotalAmountVnd,
		&i.IsNonCashOverride,
		&i.OverrideReason,
		&i.AccompanyingDocuments,
	)
	return i, err
}

const getCashReceiptByID = `-- name: GetCashReceiptByID :one
SELECT 
    id,
    voucher_id,
    company_profile_id,
    payer_name,
    payer_address,
    reason,
    cash_account_id,
    total_amount_vnd,
    accompanying_documents
FROM cash_receipts
WHERE id = ?
`

func (q *Queries) GetCashReceiptByID(ctx context.Context, id string) (CashReceipt, error) {
	row := q.db.QueryRowContext(ctx, getCashReceiptByID, id)
	var i CashReceipt
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.CompanyProfileID,
		&i.PayerName,
		&i.PayerAddress,
		&i.Reason,
		&i.CashAccountID,
		&i.TotalAmountVnd,
		&i.AccompanyingDocuments,
	)
	return i, err
}

const getCashReceiptByVoucherID = `-- name: GetCashReceiptByVoucherID :one
SELECT 
    id,
    voucher_id,
    company_profile_id,
    payer_name,
    payer_address,
    reason,
    cash_account_id,
    total_amount_vnd,
    accompanying_documents
FROM cash_receipts
WHERE voucher_id = ?
`

func (q *Queries) GetCashReceiptByVoucherID(ctx context.Context, voucherID string) (CashReceipt, error) {
	row := q.db.QueryRowContext(ctx, getCashReceiptByVoucherID, voucherID)
	var i CashReceipt
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.CompanyProfileID,
		&i.PayerName,
		&i.PayerAddress,
		&i.Reason,
		&i.CashAccountID,
		&i.TotalAmountVnd,
		&i.AccompanyingDocuments,
	)
	return i, err
}
