// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalogs.sql

package mariadb

import (
	"context"
	"database/sql"
	"time"
)

const createBankAccount = `-- name: CreateBankAccount :exec

INSERT INTO bank_accounts (
    id, company_profile_id, branch_id, account_number, bank_name, bank_code, branch_name, currency_code, gl_account_id, is_active, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    branch_id = VALUES(branch_id),
    bank_name = VALUES(bank_name),
    bank_code = VALUES(bank_code),
    branch_name = VALUES(branch_name),
    currency_code = VALUES(currency_code),
    gl_account_id = VALUES(gl_account_id),
    is_active = VALUES(is_active),
    updated_at = VALUES(updated_at)
`

type CreateBankAccountParams struct {
	ID               string         `json:"id"`
	CompanyProfileID string         `json:"company_profile_id"`
	BranchID         sql.NullString `json:"branch_id"`
	AccountNumber    string         `json:"account_number"`
	BankName         string         `json:"bank_name"`
	BankCode         string         `json:"bank_code"`
	BranchName       sql.NullString `json:"branch_name"`
	CurrencyCode     string         `json:"currency_code"`
	GlAccountID      string         `json:"gl_account_id"`
	IsActive         bool           `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

// ============================================================================
// BankAccount Queries
// ============================================================================
func (q *Queries) CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) error {
	_, err := q.db.ExecContext(ctx, createBankAccount,
		arg.ID,
		arg.CompanyProfileID,
		arg.BranchID,
		arg.AccountNumber,
		arg.BankName,
		arg.BankCode,
		arg.BranchName,
		arg.CurrencyCode,
		arg.GlAccountID,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createCustomer = `-- name: CreateCustomer :exec

INSERT INTO customers (
    id, company_profile_id, code, name, tax_code, address, phone, email, contact_person,
    payment_term_days, credit_limit, enforce_credit_limit, default_ar_account_id, is_active, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    tax_code = VALUES(tax_code),
    address = VALUES(address),
    phone = VALUES(phone),
    email = VALUES(email),
    contact_person = VALUES(contact_person),
    payment_term_days = VALUES(payment_term_days),
    credit_limit = VALUES(credit_limit),
    enforce_credit_limit = VALUES(enforce_credit_limit),
    default_ar_account_id = VALUES(default_ar_account_id),
    is_active = VALUES(is_active),
    updated_at = VALUES(updated_at)
`

type CreateCustomerParams struct {
	ID                 string         `json:"id"`
	CompanyProfileID   string         `json:"company_profile_id"`
	Code               string         `json:"code"`
	Name               string         `json:"name"`
	TaxCode            sql.NullString `json:"tax_code"`
	Address            sql.NullString `json:"address"`
	Phone              sql.NullString `json:"phone"`
	Email              sql.NullString `json:"email"`
	ContactPerson      sql.NullString `json:"contact_person"`
	PaymentTermDays    int32          `json:"payment_term_days"`
	CreditLimit        string         `json:"credit_limit"`
	EnforceCreditLimit bool           `json:"enforce_credit_limit"`
	DefaultArAccountID string         `json:"default_ar_account_id"`
	IsActive           bool           `json:"is_active"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

// ============================================================================
// Customer Queries
// ============================================================================
func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) error {
	_, err := q.db.ExecContext(ctx, createCustomer,
		arg.ID,
		arg.CompanyProfileID,
		arg.Code,
		arg.Name,
		arg.TaxCode,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.ContactPerson,
		arg.PaymentTermDays,
		arg.CreditLimit,
		arg.EnforceCreditLimit,
		arg.DefaultArAccountID,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createEmployee = `-- name: CreateEmployee :exec

INSERT INTO employees (
    id, company_profile_id, branch_id, code, full_name, department, position,
    citizen_id, tax_code, social_insurance_no, base_salary, salary_coefficient,
    bank_account_number, bank_name, default_advance_acc, default_payroll_acc,
    is_active, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    branch_id = VALUES(branch_id),
    full_name = VALUES(full_name),
    department = VALUES(department),
    position = VALUES(position),
    citizen_id = VALUES(citizen_id),
    tax_code = VALUES(tax_code),
    social_insurance_no = VALUES(social_insurance_no),
    base_salary = VALUES(base_salary),
    salary_coefficient = VALUES(salary_coefficient),
    bank_account_number = VALUES(bank_account_number),
    bank_name = VALUES(bank_name),
    default_advance_acc = VALUES(default_advance_acc),
    default_payroll_acc = VALUES(default_payroll_acc),
    is_active = VALUES(is_active),
    updated_at = VALUES(updated_at)
`

type CreateEmployeeParams struct {
	ID                string         `json:"id"`
	CompanyProfileID  string         `json:"company_profile_id"`
	BranchID          sql.NullString `json:"branch_id"`
	Code              string         `json:"code"`
	FullName          string         `json:"full_name"`
	Department        string         `json:"department"`
	Position          string         `json:"position"`
	CitizenID         string         `json:"citizen_id"`
	TaxCode           sql.NullString `json:"tax_code"`
	SocialInsuranceNo string         `json:"social_insurance_no"`
	BaseSalary        string         `json:"base_salary"`
	SalaryCoefficient string         `json:"salary_coefficient"`
	BankAccountNumber sql.NullString `json:"bank_account_number"`
	BankName          sql.NullString `json:"bank_name"`
	DefaultAdvanceAcc string         `json:"default_advance_acc"`
	DefaultPayrollAcc string         `json:"default_payroll_acc"`
	IsActive          bool           `json:"is_active"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

// ============================================================================
// Employee Queries
// ============================================================================
func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) error {
	_, err := q.db.ExecContext(ctx, createEmployee,
		arg.ID,
		arg.CompanyProfileID,
		arg.BranchID,
		arg.Code,
		arg.FullName,
		arg.Department,
		arg.Position,
		arg.CitizenID,
		arg.TaxCode,
		arg.SocialInsuranceNo,
		arg.BaseSalary,
		arg.SalaryCoefficient,
		arg.BankAccountNumber,
		arg.BankName,
		arg.DefaultAdvanceAcc,
		arg.DefaultPayrollAcc,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createItem = `-- name: CreateItem :exec

INSERT INTO items (
    id, company_profile_id, code, name, barcode, item_type, base_uom_id,
    default_warehouse_id, inventory_account_id, cogs_account_id, revenue_account_id,
    default_vat_rate, standard_cost_price, standard_sale_price, is_active, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    barcode = VALUES(barcode),
    item_type = VALUES(item_type),
    base_uom_id = VALUES(base_uom_id),
    default_warehouse_id = VALUES(default_warehouse_id),
    inventory_account_id = VALUES(inventory_account_id),
    cogs_account_id = VALUES(cogs_account_id),
    revenue_account_id = VALUES(revenue_account_id),
    default_vat_rate = VALUES(default_vat_rate),
    standard_cost_price = VALUES(standard_cost_price),
    standard_sale_price = VALUES(standard_sale_price),
    is_active = VALUES(is_active),
    updated_at = VALUES(updated_at)
`

type CreateItemParams struct {
	ID                 string         `json:"id"`
	CompanyProfileID   string         `json:"company_profile_id"`
	Code               string         `json:"code"`
	Name               string         `json:"name"`
	Barcode            sql.NullString `json:"barcode"`
	ItemType           ItemsItemType  `json:"item_type"`
	BaseUomID          string         `json:"base_uom_id"`
	DefaultWarehouseID sql.NullString `json:"default_warehouse_id"`
	InventoryAccountID sql.NullString `json:"inventory_account_id"`
	CogsAccountID      string         `json:"cogs_account_id"`
	RevenueAccountID   string         `json:"revenue_account_id"`
	DefaultVatRate     string         `json:"default_vat_rate"`
	StandardCostPrice  string         `json:"standard_cost_price"`
	StandardSalePrice  string         `json:"standard_sale_price"`
	IsActive           bool           `json:"is_active"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

// ============================================================================
// Item Queries
// ============================================================================
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.ID,
		arg.CompanyProfileID,
		arg.Code,
		arg.Name,
		arg.Barcode,
		arg.ItemType,
		arg.BaseUomID,
		arg.DefaultWarehouseID,
		arg.InventoryAccountID,
		arg.CogsAccountID,
		arg.RevenueAccountID,
		arg.DefaultVatRate,
		arg.StandardCostPrice,
		arg.StandardSalePrice,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createUOM = `-- name: CreateUOM :exec

INSERT INTO unit_of_measures (
    id, company_profile_id, code, name, description, is_active, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    description = VALUES(description),
    is_active = VALUES(is_active),
    updated_at = VALUES(updated_at)
`

type CreateUOMParams struct {
	ID               string         `json:"id"`
	CompanyProfileID string         `json:"company_profile_id"`
	Code             string         `json:"code"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	IsActive         bool           `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

// ============================================================================
// UnitOfMeasure Queries
// ============================================================================
func (q *Queries) CreateUOM(ctx context.Context, arg CreateUOMParams) error {
	_, err := q.db.ExecContext(ctx, createUOM,
		arg.ID,
		arg.CompanyProfileID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createUOMConversion = `-- name: CreateUOMConversion :exec

INSERT INTO uom_conversions (
    id, company_profile_id, item_id, from_uom_id, to_uom_id, multiplier, conversion_type, is_active, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    multiplier = VALUES(multiplier),
    conversion_type = VALUES(conversion_type),
    is_active = VALUES(is_active),
    updated_at = VALUES(updated_at)
`

type CreateUOMConversionParams struct {
	ID               string                       `json:"id"`
	CompanyProfileID string                       `json:"company_profile_id"`
	ItemID           sql.NullString               `json:"item_id"`
	FromUomID        string                       `json:"from_uom_id"`
	ToUomID          string                       `json:"to_uom_id"`
	Multiplier       string                       `json:"multiplier"`
	ConversionType   UomConversionsConversionType `json:"conversion_type"`
	IsActive         bool                         `json:"is_active"`
	CreatedAt        time.Time                    `json:"created_at"`
	UpdatedAt        time.Time                    `json:"updated_at"`
}

// ============================================================================
// UOMConversion Queries
// ============================================================================
func (q *Queries) CreateUOMConversion(ctx context.Context, arg CreateUOMConversionParams) error {
	_, err := q.db.ExecContext(ctx, createUOMConversion,
		arg.ID,
		arg.CompanyProfileID,
		arg.ItemID,
		arg.FromUomID,
		arg.ToUomID,
		arg.Multiplier,
		arg.ConversionType,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createVendor = `-- name: CreateVendor :exec

INSERT INTO vendors (
    id, company_profile_id, code, name, tax_code, address, phone, email, contact_person,
    bank_account_number, bank_name, bank_branch, payment_term_days, default_ap_account_id, is_active, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    tax_code = VALUES(tax_code),
    address = VALUES(address),
    phone = VALUES(phone),
    email = VALUES(email),
    contact_person = VALUES(contact_person),
    bank_account_number = VALUES(bank_account_number),
    bank_name = VALUES(bank_name),
    bank_branch = VALUES(bank_branch),
    payment_term_days = VALUES(payment_term_days),
    default_ap_account_id = VALUES(default_ap_account_id),
    is_active = VALUES(is_active),
    updated_at = VALUES(updated_at)
`

type CreateVendorParams struct {
	ID                 string         `json:"id"`
	CompanyProfileID   string         `json:"company_profile_id"`
	Code               string         `json:"code"`
	Name               string         `json:"name"`
	TaxCode            sql.NullString `json:"tax_code"`
	Address            sql.NullString `json:"address"`
	Phone              sql.NullString `json:"phone"`
	Email              sql.NullString `json:"email"`
	ContactPerson      sql.NullString `json:"contact_person"`
	BankAccountNumber  sql.NullString `json:"bank_account_number"`
	BankName           sql.NullString `json:"bank_name"`
	BankBranch         sql.NullString `json:"bank_branch"`
	PaymentTermDays    int32          `json:"payment_term_days"`
	DefaultApAccountID string         `json:"default_ap_account_id"`
	IsActive           bool           `json:"is_active"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

// ============================================================================
// Vendor Queries
// ============================================================================
func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) error {
	_, err := q.db.ExecContext(ctx, createVendor,
		arg.ID,
		arg.CompanyProfileID,
		arg.Code,
		arg.Name,
		arg.TaxCode,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.ContactPerson,
		arg.BankAccountNumber,
		arg.BankName,
		arg.BankBranch,
		arg.PaymentTermDays,
		arg.DefaultApAccountID,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createWarehouse = `-- name: CreateWarehouse :exec

INSERT INTO warehouses (
    id, company_profile_id, branch_id, code, name, address, default_account_id, is_active, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    branch_id = VALUES(branch_id),
    name = VALUES(name),
    address = VALUES(address),
    default_account_id = VALUES(default_account_id),
    is_active = VALUES(is_active),
    updated_at = VALUES(updated_at)
`

type CreateWarehouseParams struct {
	ID               string         `json:"id"`
	CompanyProfileID string         `json:"company_profile_id"`
	BranchID         sql.NullString `json:"branch_id"`
	Code             string         `json:"code"`
	Name             string         `json:"name"`
	Address          sql.NullString `json:"address"`
	DefaultAccountID string         `json:"default_account_id"`
	IsActive         bool           `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

// ============================================================================
// Warehouse Queries
// ============================================================================
func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) error {
	_, err := q.db.ExecContext(ctx, createWarehouse,
		arg.ID,
		arg.CompanyProfileID,
		arg.BranchID,
		arg.Code,
		arg.Name,
		arg.Address,
		arg.DefaultAccountID,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getBankAccountByID = `-- name: GetBankAccountByID :one
SELECT id, company_profile_id, branch_id, account_number, bank_name, bank_code, branch_name, currency_code, gl_account_id, is_active, created_at, updated_at FROM bank_accounts
WHERE id = ? LIMIT 1
`

func (q *Queries) GetBankAccountByID(ctx context.Context, id string) (BankAccount, error) {
	row := q.db.QueryRowContext(ctx, getBankAccountByID, id)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.BranchID,
		&i.AccountNumber,
		&i.BankName,
		&i.BankCode,
		&i.BranchName,
		&i.CurrencyCode,
		&i.GlAccountID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBankAccountByNumber = `-- name: GetBankAccountByNumber :one
SELECT id, company_profile_id, branch_id, account_number, bank_name, bank_code, branch_name, currency_code, gl_account_id, is_active, created_at, updated_at FROM bank_accounts
WHERE company_profile_id = ? AND account_number = ? LIMIT 1
`

type GetBankAccountByNumberParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	AccountNumber    string `json:"account_number"`
}

func (q *Queries) GetBankAccountByNumber(ctx context.Context, arg GetBankAccountByNumberParams) (BankAccount, error) {
	row := q.db.QueryRowContext(ctx, getBankAccountByNumber, arg.CompanyProfileID, arg.AccountNumber)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.BranchID,
		&i.AccountNumber,
		&i.BankName,
		&i.BankCode,
		&i.BranchName,
		&i.CurrencyCode,
		&i.GlAccountID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByCode = `-- name: GetCustomerByCode :one
SELECT id, company_profile_id, code, name, tax_code, address, phone, email, contact_person, payment_term_days, credit_limit, enforce_credit_limit, default_ar_account_id, is_active, created_at, updated_at FROM customers
WHERE company_profile_id = ? AND code = ? LIMIT 1
`

type GetCustomerByCodeParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	Code             string `json:"code"`
}

func (q *Queries) GetCustomerByCode(ctx context.Context, arg GetCustomerByCodeParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByCode, arg.CompanyProfileID, arg.Code)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Code,
		&i.Name,
		&i.TaxCode,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactPerson,
		&i.PaymentTermDays,
		&i.CreditLimit,
		&i.EnforceCreditLimit,
		&i.DefaultArAccountID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, company_profile_id, code, name, tax_code, address, phone, email, contact_person, payment_term_days, credit_limit, enforce_credit_limit, default_ar_account_id, is_active, created_at, updated_at FROM customers
WHERE id = ? LIMIT 1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Code,
		&i.Name,
		&i.TaxCode,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactPerson,
		&i.PaymentTermDays,
		&i.CreditLimit,
		&i.EnforceCreditLimit,
		&i.DefaultArAccountID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByTaxCode = `-- name: GetCustomerByTaxCode :one
SELECT id, company_profile_id, code, name, tax_code, address, phone, email, contact_person, payment_term_days, credit_limit, enforce_credit_limit, default_ar_account_id, is_active, created_at, updated_at FROM customers
WHERE company_profile_id = ? AND tax_code = ? LIMIT 1
`

type GetCustomerByTaxCodeParams struct {
	CompanyProfileID string         `json:"company_profile_id"`
	TaxCode          sql.NullString `json:"tax_code"`
}

func (q *Queries) GetCustomerByTaxCode(ctx context.Context, arg GetCustomerByTaxCodeParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByTaxCode, arg.CompanyProfileID, arg.TaxCode)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Code,
		&i.Name,
		&i.TaxCode,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactPerson,
		&i.PaymentTermDays,
		&i.CreditLimit,
		&i.EnforceCreditLimit,
		&i.DefaultArAccountID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeByCitizenID = `-- name: GetEmployeeByCitizenID :one
SELECT id, company_profile_id, branch_id, code, full_name, department, position, citizen_id, tax_code, social_insurance_no, base_salary, salary_coefficient, bank_account_number, bank_name, default_advance_acc, default_payroll_acc, is_active, created_at, updated_at FROM employees
WHERE company_profile_id = ? AND citizen_id = ? LIMIT 1
`

type GetEmployeeByCitizenIDParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	CitizenID        string `json:"citizen_id"`
}

func (q *Queries) GetEmployeeByCitizenID(ctx context.Context, arg GetEmployeeByCitizenIDParams) (Employee, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeByCitizenID, arg.CompanyProfileID, arg.CitizenID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.BranchID,
		&i.Code,
		&i.FullName,
		&i.Department,
		&i.Position,
		&i.CitizenID,
		&i.TaxCode,
		&i.SocialInsuranceNo,
		&i.BaseSalary,
		&i.SalaryCoefficient,
		&i.BankAccountNumber,
		&i.BankName,
		&i.DefaultAdvanceAcc,
		&i.DefaultPayrollAcc,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeByCode = `-- name: GetEmployeeByCode :one
SELECT id, company_profile_id, branch_id, code, full_name, department, position, citizen_id, tax_code, social_insurance_no, base_salary, salary_coefficient, bank_account_number, bank_name, default_advance_acc, default_payroll_acc, is_active, created_at, updated_at FROM employees
WHERE company_profile_id = ? AND code = ? LIMIT 1
`

type GetEmployeeByCodeParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	Code             string `json:"code"`
}

func (q *Queries) GetEmployeeByCode(ctx context.Context, arg GetEmployeeByCodeParams) (Employee, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeByCode, arg.CompanyProfileID, arg.Code)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.BranchID,
		&i.Code,
		&i.FullName,
		&i.Department,
		&i.Position,
		&i.CitizenID,
		&i.TaxCode,
		&i.SocialInsuranceNo,
		&i.BaseSalary,
		&i.SalaryCoefficient,
		&i.BankAccountNumber,
		&i.BankName,
		&i.DefaultAdvanceAcc,
		&i.DefaultPayrollAcc,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT id, company_profile_id, branch_id, code, full_name, department, position, citizen_id, tax_code, social_insurance_no, base_salary, salary_coefficient, bank_account_number, bank_name, default_advance_acc, default_payroll_acc, is_active, created_at, updated_at FROM employees
WHERE id = ? LIMIT 1
`

func (q *Queries) GetEmployeeByID(ctx context.Context, id string) (Employee, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeByID, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.BranchID,
		&i.Code,
		&i.FullName,
		&i.Department,
		&i.Position,
		&i.CitizenID,
		&i.TaxCode,
		&i.SocialInsuranceNo,
		&i.BaseSalary,
		&i.SalaryCoefficient,
		&i.BankAccountNumber,
		&i.BankName,
		&i.DefaultAdvanceAcc,
		&i.DefaultPayrollAcc,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemByCode = `-- name: GetItemByCode :one
SELECT id, company_profile_id, code, name, barcode, item_type, base_uom_id, default_warehouse_id, inventory_account_id, cogs_account_id, revenue_account_id, default_vat_rate, standard_cost_price, standard_sale_price, is_active, created_at, updated_at FROM items
WHERE company_profile_id = ? AND code = ? LIMIT 1
`

type GetItemByCodeParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	Code             string `json:"code"`
}

func (q *Queries) GetItemByCode(ctx context.Context, arg GetItemByCodeParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByCode, arg.CompanyProfileID, arg.Code)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Code,
		&i.Name,
		&i.Barcode,
		&i.ItemType,
		&i.BaseUomID,
		&i.DefaultWarehouseID,
		&i.InventoryAccountID,
		&i.CogsAccountID,
		&i.RevenueAccountID,
		&i.DefaultVatRate,
		&i.StandardCostPrice,
		&i.StandardSalePrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, company_profile_id, code, name, barcode, item_type, base_uom_id, default_warehouse_id, inventory_account_id, cogs_account_id, revenue_account_id, default_vat_rate, standard_cost_price, standard_sale_price, is_active, created_at, updated_at FROM items
WHERE id = ? LIMIT 1
`

func (q *Queries) GetItemByID(ctx context.Context, id string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Code,
		&i.Name,
		&i.Barcode,
		&i.ItemType,
		&i.BaseUomID,
		&i.DefaultWarehouseID,
		&i.InventoryAccountID,
		&i.CogsAccountID,
		&i.RevenueAccountID,
		&i.DefaultVatRate,
		&i.StandardCostPrice,
		&i.StandardSalePrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUOMByCode = `-- name: GetUOMByCode :one
SELECT id, company_profile_id, code, name, description, is_active, created_at, updated_at FROM unit_of_measures
WHERE company_profile_id = ? AND code = ? LIMIT 1
`

type GetUOMByCodeParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	Code             string `json:"code"`
}

func (q *Queries) GetUOMByCode(ctx context.Context, arg GetUOMByCodeParams) (UnitOfMeasure, error) {
	row := q.db.QueryRowContext(ctx, getUOMByCode, arg.CompanyProfileID, arg.Code)
	var i UnitOfMeasure
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUOMByID = `-- name: GetUOMByID :one
SELECT id, company_profile_id, code, name, description, is_active, created_at, updated_at FROM unit_of_measures
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUOMByID(ctx context.Context, id string) (UnitOfMeasure, error) {
	row := q.db.QueryRowContext(ctx, getUOMByID, id)
	var i UnitOfMeasure
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUOMConversion = `-- name: GetUOMConversion :one
SELECT id, company_profile_id, item_id, from_uom_id, to_uom_id, multiplier, conversion_type, is_active, created_at, updated_at FROM uom_conversions
WHERE company_profile_id = ?
  AND ((item_id = ? OR (item_id IS NULL AND ? IS NULL)))
  AND from_uom_id = ?
  AND to_uom_id = ?
LIMIT 1
`

type GetUOMConversionParams struct {
	CompanyProfileID string         `json:"company_profile_id"`
	ItemID           sql.NullString `json:"item_id"`
	Column3          interface{}    `json:"column_3"`
	FromUomID        string         `json:"from_uom_id"`
	ToUomID          string         `json:"to_uom_id"`
}

func (q *Queries) GetUOMConversion(ctx context.Context, arg GetUOMConversionParams) (UomConversion, error) {
	row := q.db.QueryRowContext(ctx, getUOMConversion,
		arg.CompanyProfileID,
		arg.ItemID,
		arg.Column3,
		arg.FromUomID,
		arg.ToUomID,
	)
	var i UomConversion
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.ItemID,
		&i.FromUomID,
		&i.ToUomID,
		&i.Multiplier,
		&i.ConversionType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorByCode = `-- name: GetVendorByCode :one
SELECT id, company_profile_id, code, name, tax_code, address, phone, email, contact_person, bank_account_number, bank_name, bank_branch, payment_term_days, default_ap_account_id, is_active, created_at, updated_at FROM vendors
WHERE company_profile_id = ? AND code = ? LIMIT 1
`

type GetVendorByCodeParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	Code             string `json:"code"`
}

func (q *Queries) GetVendorByCode(ctx context.Context, arg GetVendorByCodeParams) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, getVendorByCode, arg.CompanyProfileID, arg.Code)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Code,
		&i.Name,
		&i.TaxCode,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactPerson,
		&i.BankAccountNumber,
		&i.BankName,
		&i.BankBranch,
		&i.PaymentTermDays,
		&i.DefaultApAccountID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorByID = `-- name: GetVendorByID :one
SELECT id, company_profile_id, code, name, tax_code, address, phone, email, contact_person, bank_account_number, bank_name, bank_branch, payment_term_days, default_ap_account_id, is_active, created_at, updated_at FROM vendors
WHERE id = ? LIMIT 1
`

func (q *Queries) GetVendorByID(ctx context.Context, id string) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, getVendorByID, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Code,
		&i.Name,
		&i.TaxCode,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactPerson,
		&i.BankAccountNumber,
		&i.BankName,
		&i.BankBranch,
		&i.PaymentTermDays,
		&i.DefaultApAccountID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorByTaxCode = `-- name: GetVendorByTaxCode :one
SELECT id, company_profile_id, code, name, tax_code, address, phone, email, contact_person, bank_account_number, bank_name, bank_branch, payment_term_days, default_ap_account_id, is_active, created_at, updated_at FROM vendors
WHERE company_profile_id = ? AND tax_code = ? LIMIT 1
`

type GetVendorByTaxCodeParams struct {
	CompanyProfileID string         `json:"company_profile_id"`
	TaxCode          sql.NullString `json:"tax_code"`
}

func (q *Queries) GetVendorByTaxCode(ctx context.Context, arg GetVendorByTaxCodeParams) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, getVendorByTaxCode, arg.CompanyProfileID, arg.TaxCode)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Code,
		&i.Name,
		&i.TaxCode,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactPerson,
		&i.BankAccountNumber,
		&i.BankName,
		&i.BankBranch,
		&i.PaymentTermDays,
		&i.DefaultApAccountID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWarehouseByCode = `-- name: GetWarehouseByCode :one
SELECT id, company_profile_id, branch_id, code, name, address, default_account_id, is_active, created_at, updated_at FROM warehouses
WHERE company_profile_id = ? AND code = ? LIMIT 1
`

type GetWarehouseByCodeParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	Code             string `json:"code"`
}

func (q *Queries) GetWarehouseByCode(ctx context.Context, arg GetWarehouseByCodeParams) (Warehouse, error) {
	row := q.db.QueryRowContext(ctx, getWarehouseByCode, arg.CompanyProfileID, arg.Code)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.BranchID,
		&i.Code,
		&i.Name,
		&i.Address,
		&i.DefaultAccountID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWarehouseByID = `-- name: GetWarehouseByID :one
SELECT id, company_profile_id, branch_id, code, name, address, default_account_id, is_active, created_at, updated_at FROM warehouses
WHERE id = ? LIMIT 1
`

func (q *Queries) GetWarehouseByID(ctx context.Context, id string) (Warehouse, error) {
	row := q.db.QueryRowContext(ctx, getWarehouseByID, id)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.BranchID,
		&i.Code,
		&i.Name,
		&i.Address,
		&i.DefaultAccountID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBankAccounts = `-- name: ListBankAccounts :many
SELECT id, company_profile_id, branch_id, account_number, bank_name, bank_code, branch_name, currency_code, gl_account_id, is_active, created_at, updated_at FROM bank_accounts
WHERE company_profile_id = ?
ORDER BY account_number ASC
`

func (q *Queries) ListBankAccounts(ctx context.Context, companyProfileID string) ([]BankAccount, error) {
	rows, err := q.db.QueryContext(ctx, listBankAccounts, companyProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankAccount
	for rows.Next() {
		var i BankAccount
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.BranchID,
			&i.AccountNumber,
			&i.BankName,
			&i.BankCode,
			&i.BranchName,
			&i.CurrencyCode,
			&i.GlAccountID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, company_profile_id, code, name, tax_code, address, phone, email, contact_person, payment_term_days, credit_limit, enforce_credit_limit, default_ar_account_id, is_active, created_at, updated_at FROM customers
WHERE company_profile_id = ?
ORDER BY code ASC
`

func (q *Queries) ListCustomers(ctx context.Context, companyProfileID string) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers, companyProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.Code,
			&i.Name,
			&i.TaxCode,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.ContactPerson,
			&i.PaymentTermDays,
			&i.CreditLimit,
			&i.EnforceCreditLimit,
			&i.DefaultArAccountID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, company_profile_id, branch_id, code, full_name, department, position, citizen_id, tax_code, social_insurance_no, base_salary, salary_coefficient, bank_account_number, bank_name, default_advance_acc, default_payroll_acc, is_active, created_at, updated_at FROM employees
WHERE company_profile_id = ?
ORDER BY code ASC
`

func (q *Queries) ListEmployees(ctx context.Context, companyProfileID string) ([]Employee, error) {
	rows, err := q.db.QueryContext(ctx, listEmployees, companyProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.BranchID,
			&i.Code,
			&i.FullName,
			&i.Department,
			&i.Position,
			&i.CitizenID,
			&i.TaxCode,
			&i.SocialInsuranceNo,
			&i.BaseSalary,
			&i.SalaryCoefficient,
			&i.BankAccountNumber,
			&i.BankName,
			&i.DefaultAdvanceAcc,
			&i.DefaultPayrollAcc,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, company_profile_id, code, name, barcode, item_type, base_uom_id, default_warehouse_id, inventory_account_id, cogs_account_id, revenue_account_id, default_vat_rate, standard_cost_price, standard_sale_price, is_active, created_at, updated_at FROM items
WHERE company_profile_id = ?
ORDER BY code ASC
`

func (q *Queries) ListItems(ctx context.Context, companyProfileID string) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItems, companyProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.Code,
			&i.Name,
			&i.Barcode,
			&i.ItemType,
			&i.BaseUomID,
			&i.DefaultWarehouseID,
			&i.InventoryAccountID,
			&i.CogsAccountID,
			&i.RevenueAccountID,
			&i.DefaultVatRate,
			&i.StandardCostPrice,
			&i.StandardSalePrice,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUOMConversionsByItem = `-- name: ListUOMConversionsByItem :many
SELECT id, company_profile_id, item_id, from_uom_id, to_uom_id, multiplier, conversion_type, is_active, created_at, updated_at FROM uom_conversions
WHERE company_profile_id = ? AND (item_id = ? OR item_id IS NULL)
ORDER BY created_at ASC
`

type ListUOMConversionsByItemParams struct {
	CompanyProfileID string         `json:"company_profile_id"`
	ItemID           sql.NullString `json:"item_id"`
}

func (q *Queries) ListUOMConversionsByItem(ctx context.Context, arg ListUOMConversionsByItemParams) ([]UomConversion, error) {
	rows, err := q.db.QueryContext(ctx, listUOMConversionsByItem, arg.CompanyProfileID, arg.ItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UomConversion
	for rows.Next() {
		var i UomConversion
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.ItemID,
			&i.FromUomID,
			&i.ToUomID,
			&i.Multiplier,
			&i.ConversionType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUOMs = `-- name: ListUOMs :many
SELECT id, company_profile_id, code, name, description, is_active, created_at, updated_at FROM unit_of_measures
WHERE company_profile_id = ?
ORDER BY code ASC
`

func (q *Queries) ListUOMs(ctx context.Context, companyProfileID string) ([]UnitOfMeasure, error) {
	rows, err := q.db.QueryContext(ctx, listUOMs, companyProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnitOfMeasure
	for rows.Next() {
		var i UnitOfMeasure
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendors = `-- name: ListVendors :many
SELECT id, company_profile_id, code, name, tax_code, address, phone, email, contact_person, bank_account_number, bank_name, bank_branch, payment_term_days, default_ap_account_id, is_active, created_at, updated_at FROM vendors
WHERE company_profile_id = ?
ORDER BY code ASC
`

func (q *Queries) ListVendors(ctx context.Context, companyProfileID string) ([]Vendor, error) {
	rows, err := q.db.QueryContext(ctx, listVendors, companyProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vendor
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.Code,
			&i.Name,
			&i.TaxCode,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.ContactPerson,
			&i.BankAccountNumber,
			&i.BankName,
			&i.BankBranch,
			&i.PaymentTermDays,
			&i.DefaultApAccountID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehouses = `-- name: ListWarehouses :many
SELECT id, company_profile_id, branch_id, code, name, address, default_account_id, is_active, created_at, updated_at FROM warehouses
WHERE company_profile_id = ?
ORDER BY code ASC
`

func (q *Queries) ListWarehouses(ctx context.Context, companyProfileID string) ([]Warehouse, error) {
	rows, err := q.db.QueryContext(ctx, listWarehouses, companyProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Warehouse
	for rows.Next() {
		var i Warehouse
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.BranchID,
			&i.Code,
			&i.Name,
			&i.Address,
			&i.DefaultAccountID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
