// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gl.sql

package mariadb

import (
	"context"
	"database/sql"
	"time"
)

const createVoucher = `-- name: CreateVoucher :exec

INSERT INTO vouchers (id, voucher_no, voucher_date, posted_date, voucher_type, description, is_posted)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateVoucherParams struct {
	ID          string              `json:"id"`
	VoucherNo   string              `json:"voucher_no"`
	VoucherDate time.Time           `json:"voucher_date"`
	PostedDate  time.Time           `json:"posted_date"`
	VoucherType VouchersVoucherType `json:"voucher_type"`
	Description sql.NullString      `json:"description"`
	IsPosted    bool                `json:"is_posted"`
}

// General Ledger Voucher Queries
func (q *Queries) CreateVoucher(ctx context.Context, arg CreateVoucherParams) error {
	_, err := q.db.ExecContext(ctx, createVoucher,
		arg.ID,
		arg.VoucherNo,
		arg.VoucherDate,
		arg.PostedDate,
		arg.VoucherType,
		arg.Description,
		arg.IsPosted,
	)
	return err
}

const createVoucherLine = `-- name: CreateVoucherLine :exec
INSERT INTO voucher_lines (id, voucher_id, line_order, debit_account_id, credit_account_id, amount, note)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateVoucherLineParams struct {
	ID              string         `json:"id"`
	VoucherID       string         `json:"voucher_id"`
	LineOrder       int32          `json:"line_order"`
	DebitAccountID  string         `json:"debit_account_id"`
	CreditAccountID string         `json:"credit_account_id"`
	Amount          string         `json:"amount"`
	Note            sql.NullString `json:"note"`
}

func (q *Queries) CreateVoucherLine(ctx context.Context, arg CreateVoucherLineParams) error {
	_, err := q.db.ExecContext(ctx, createVoucherLine,
		arg.ID,
		arg.VoucherID,
		arg.LineOrder,
		arg.DebitAccountID,
		arg.CreditAccountID,
		arg.Amount,
		arg.Note,
	)
	return err
}

const listVoucherLinesByVoucherID = `-- name: ListVoucherLinesByVoucherID :many
SELECT id, voucher_id, line_order, debit_account_id, credit_account_id, amount, note
FROM voucher_lines
WHERE voucher_id = ?
ORDER BY line_order ASC
`

func (q *Queries) ListVoucherLinesByVoucherID(ctx context.Context, voucherID string) ([]VoucherLine, error) {
	rows, err := q.db.QueryContext(ctx, listVoucherLinesByVoucherID, voucherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoucherLine
	for rows.Next() {
		var i VoucherLine
		if err := rows.Scan(
			&i.ID,
			&i.VoucherID,
			&i.LineOrder,
			&i.DebitAccountID,
			&i.CreditAccountID,
			&i.Amount,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
