// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gl.sql

package mariadb

import (
	"context"
	"database/sql"
	"time"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, code, name, parent_id, account_type, nature, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAccountParams struct {
	ID          string              `json:"id"`
	Code        string              `json:"code"`
	Name        string              `json:"name"`
	ParentID    sql.NullString      `json:"parent_id"`
	AccountType AccountsAccountType `json:"account_type"`
	Nature      AccountsNature      `json:"nature"`
	IsActive    bool                `json:"is_active"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.ParentID,
		arg.AccountType,
		arg.Nature,
		arg.IsActive,
	)
	return err
}

const createVoucher = `-- name: CreateVoucher :exec
INSERT INTO vouchers (id, voucher_no, voucher_date, posted_date, voucher_type, description, is_posted)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateVoucherParams struct {
	ID          string              `json:"id"`
	VoucherNo   string              `json:"voucher_no"`
	VoucherDate time.Time           `json:"voucher_date"`
	PostedDate  time.Time           `json:"posted_date"`
	VoucherType VouchersVoucherType `json:"voucher_type"`
	Description sql.NullString      `json:"description"`
	IsPosted    bool                `json:"is_posted"`
}

func (q *Queries) CreateVoucher(ctx context.Context, arg CreateVoucherParams) error {
	_, err := q.db.ExecContext(ctx, createVoucher,
		arg.ID,
		arg.VoucherNo,
		arg.VoucherDate,
		arg.PostedDate,
		arg.VoucherType,
		arg.Description,
		arg.IsPosted,
	)
	return err
}

const createVoucherLine = `-- name: CreateVoucherLine :exec
INSERT INTO voucher_lines (id, voucher_id, line_order, debit_account_id, credit_account_id, amount, note)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateVoucherLineParams struct {
	ID              string         `json:"id"`
	VoucherID       string         `json:"voucher_id"`
	LineOrder       int32          `json:"line_order"`
	DebitAccountID  string         `json:"debit_account_id"`
	CreditAccountID string         `json:"credit_account_id"`
	Amount          string         `json:"amount"`
	Note            sql.NullString `json:"note"`
}

func (q *Queries) CreateVoucherLine(ctx context.Context, arg CreateVoucherLineParams) error {
	_, err := q.db.ExecContext(ctx, createVoucherLine,
		arg.ID,
		arg.VoucherID,
		arg.LineOrder,
		arg.DebitAccountID,
		arg.CreditAccountID,
		arg.Amount,
		arg.Note,
	)
	return err
}

const getAccountByCode = `-- name: GetAccountByCode :one
SELECT id, code, name, parent_id, account_type, nature, is_active, created_at, updated_at
FROM accounts
WHERE code = ? LIMIT 1
`

func (q *Queries) GetAccountByCode(ctx context.Context, code string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByCode, code)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.AccountType,
		&i.Nature,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAccounts = `-- name: ListActiveAccounts :many
SELECT id, code, name, parent_id, account_type, nature, is_active, created_at, updated_at
FROM accounts
WHERE is_active = TRUE
ORDER BY code ASC
`

func (q *Queries) ListActiveAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ParentID,
			&i.AccountType,
			&i.Nature,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoucherLinesByVoucherID = `-- name: ListVoucherLinesByVoucherID :many
SELECT id, voucher_id, line_order, debit_account_id, credit_account_id, amount, note
FROM voucher_lines
WHERE voucher_id = ?
ORDER BY line_order ASC
`

func (q *Queries) ListVoucherLinesByVoucherID(ctx context.Context, voucherID string) ([]VoucherLine, error) {
	rows, err := q.db.QueryContext(ctx, listVoucherLinesByVoucherID, voucherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoucherLine
	for rows.Next() {
		var i VoucherLine
		if err := rows.Scan(
			&i.ID,
			&i.VoucherID,
			&i.LineOrder,
			&i.DebitAccountID,
			&i.CreditAccountID,
			&i.Amount,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
