// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mariadb

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type AccountsAccountType string

const (
	AccountsAccountTypeASSET     AccountsAccountType = "ASSET"
	AccountsAccountTypeLIABILITY AccountsAccountType = "LIABILITY"
	AccountsAccountTypeEQUITY    AccountsAccountType = "EQUITY"
	AccountsAccountTypeREVENUE   AccountsAccountType = "REVENUE"
	AccountsAccountTypeEXPENSE   AccountsAccountType = "EXPENSE"
)

func (e *AccountsAccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountsAccountType(s)
	case string:
		*e = AccountsAccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountsAccountType: %T", src)
	}
	return nil
}

type NullAccountsAccountType struct {
	AccountsAccountType AccountsAccountType `json:"accounts_account_type"`
	Valid               bool                `json:"valid"` // Valid is true if AccountsAccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountsAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountsAccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountsAccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountsAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountsAccountType), nil
}

type AccountsNature string

const (
	AccountsNatureDEBIT  AccountsNature = "DEBIT"
	AccountsNatureCREDIT AccountsNature = "CREDIT"
	AccountsNatureDUAL   AccountsNature = "DUAL"
)

func (e *AccountsNature) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountsNature(s)
	case string:
		*e = AccountsNature(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountsNature: %T", src)
	}
	return nil
}

type NullAccountsNature struct {
	AccountsNature AccountsNature `json:"accounts_nature"`
	Valid          bool           `json:"valid"` // Valid is true if AccountsNature is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountsNature) Scan(value interface{}) error {
	if value == nil {
		ns.AccountsNature, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountsNature.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountsNature) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountsNature), nil
}

type VouchersVoucherType string

const (
	VouchersVoucherTypeSALES       VouchersVoucherType = "SALES"
	VouchersVoucherTypePURCHASE    VouchersVoucherType = "PURCHASE"
	VouchersVoucherTypeCASHRECEIPT VouchersVoucherType = "CASH_RECEIPT"
	VouchersVoucherTypeCASHPAYMENT VouchersVoucherType = "CASH_PAYMENT"
	VouchersVoucherTypeGENERAL     VouchersVoucherType = "GENERAL"
)

func (e *VouchersVoucherType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VouchersVoucherType(s)
	case string:
		*e = VouchersVoucherType(s)
	default:
		return fmt.Errorf("unsupported scan type for VouchersVoucherType: %T", src)
	}
	return nil
}

type NullVouchersVoucherType struct {
	VouchersVoucherType VouchersVoucherType `json:"vouchers_voucher_type"`
	Valid               bool                `json:"valid"` // Valid is true if VouchersVoucherType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVouchersVoucherType) Scan(value interface{}) error {
	if value == nil {
		ns.VouchersVoucherType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VouchersVoucherType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVouchersVoucherType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VouchersVoucherType), nil
}

type Account struct {
	ID          string              `json:"id"`
	Code        string              `json:"code"`
	Name        string              `json:"name"`
	ParentID    sql.NullString      `json:"parent_id"`
	AccountType AccountsAccountType `json:"account_type"`
	Nature      AccountsNature      `json:"nature"`
	IsActive    bool                `json:"is_active"`
	CreatedAt   time.Time           `json:"created_at"`
	UpdatedAt   time.Time           `json:"updated_at"`
}

type AccountingPeriod struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	IsClosed  bool      `json:"is_closed"`
	CreatedAt time.Time `json:"created_at"`
}

type Voucher struct {
	ID          string              `json:"id"`
	VoucherNo   string              `json:"voucher_no"`
	VoucherDate time.Time           `json:"voucher_date"`
	PostedDate  time.Time           `json:"posted_date"`
	VoucherType VouchersVoucherType `json:"voucher_type"`
	Description sql.NullString      `json:"description"`
	IsPosted    bool                `json:"is_posted"`
	CreatedAt   time.Time           `json:"created_at"`
}

type VoucherLine struct {
	ID              string         `json:"id"`
	VoucherID       string         `json:"voucher_id"`
	LineOrder       int32          `json:"line_order"`
	DebitAccountID  string         `json:"debit_account_id"`
	CreditAccountID string         `json:"credit_account_id"`
	Amount          string         `json:"amount"`
	Note            sql.NullString `json:"note"`
}
