// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mariadb

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type AccountsAccountType string

const (
	AccountsAccountTypeASSET     AccountsAccountType = "ASSET"
	AccountsAccountTypeLIABILITY AccountsAccountType = "LIABILITY"
	AccountsAccountTypeEQUITY    AccountsAccountType = "EQUITY"
	AccountsAccountTypeREVENUE   AccountsAccountType = "REVENUE"
	AccountsAccountTypeEXPENSE   AccountsAccountType = "EXPENSE"
)

func (e *AccountsAccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountsAccountType(s)
	case string:
		*e = AccountsAccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountsAccountType: %T", src)
	}
	return nil
}

type NullAccountsAccountType struct {
	AccountsAccountType AccountsAccountType `json:"accounts_account_type"`
	Valid               bool                `json:"valid"` // Valid is true if AccountsAccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountsAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountsAccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountsAccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountsAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountsAccountType), nil
}

type AccountsNature string

const (
	AccountsNatureDEBIT  AccountsNature = "DEBIT"
	AccountsNatureCREDIT AccountsNature = "CREDIT"
	AccountsNatureDUAL   AccountsNature = "DUAL"
)

func (e *AccountsNature) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountsNature(s)
	case string:
		*e = AccountsNature(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountsNature: %T", src)
	}
	return nil
}

type NullAccountsNature struct {
	AccountsNature AccountsNature `json:"accounts_nature"`
	Valid          bool           `json:"valid"` // Valid is true if AccountsNature is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountsNature) Scan(value interface{}) error {
	if value == nil {
		ns.AccountsNature, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountsNature.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountsNature) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountsNature), nil
}

type BranchOrgUnitsAccountingGovernance string

const (
	BranchOrgUnitsAccountingGovernanceINDEPENDENT BranchOrgUnitsAccountingGovernance = "INDEPENDENT"
	BranchOrgUnitsAccountingGovernanceDEPENDENT   BranchOrgUnitsAccountingGovernance = "DEPENDENT"
	BranchOrgUnitsAccountingGovernanceCOSTCENTER  BranchOrgUnitsAccountingGovernance = "COST_CENTER"
)

func (e *BranchOrgUnitsAccountingGovernance) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BranchOrgUnitsAccountingGovernance(s)
	case string:
		*e = BranchOrgUnitsAccountingGovernance(s)
	default:
		return fmt.Errorf("unsupported scan type for BranchOrgUnitsAccountingGovernance: %T", src)
	}
	return nil
}

type NullBranchOrgUnitsAccountingGovernance struct {
	BranchOrgUnitsAccountingGovernance BranchOrgUnitsAccountingGovernance `json:"branch_org_units_accounting_governance"`
	Valid                              bool                               `json:"valid"` // Valid is true if BranchOrgUnitsAccountingGovernance is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBranchOrgUnitsAccountingGovernance) Scan(value interface{}) error {
	if value == nil {
		ns.BranchOrgUnitsAccountingGovernance, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BranchOrgUnitsAccountingGovernance.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBranchOrgUnitsAccountingGovernance) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BranchOrgUnitsAccountingGovernance), nil
}

type BranchOrgUnitsTaxFilingMechanism string

const (
	BranchOrgUnitsTaxFilingMechanismCENTRALIZED   BranchOrgUnitsTaxFilingMechanism = "CENTRALIZED"
	BranchOrgUnitsTaxFilingMechanismDECENTRALIZED BranchOrgUnitsTaxFilingMechanism = "DECENTRALIZED"
	BranchOrgUnitsTaxFilingMechanismALLOCATED     BranchOrgUnitsTaxFilingMechanism = "ALLOCATED"
)

func (e *BranchOrgUnitsTaxFilingMechanism) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BranchOrgUnitsTaxFilingMechanism(s)
	case string:
		*e = BranchOrgUnitsTaxFilingMechanism(s)
	default:
		return fmt.Errorf("unsupported scan type for BranchOrgUnitsTaxFilingMechanism: %T", src)
	}
	return nil
}

type NullBranchOrgUnitsTaxFilingMechanism struct {
	BranchOrgUnitsTaxFilingMechanism BranchOrgUnitsTaxFilingMechanism `json:"branch_org_units_tax_filing_mechanism"`
	Valid                            bool                             `json:"valid"` // Valid is true if BranchOrgUnitsTaxFilingMechanism is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBranchOrgUnitsTaxFilingMechanism) Scan(value interface{}) error {
	if value == nil {
		ns.BranchOrgUnitsTaxFilingMechanism, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BranchOrgUnitsTaxFilingMechanism.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBranchOrgUnitsTaxFilingMechanism) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BranchOrgUnitsTaxFilingMechanism), nil
}

type BranchOrgUnitsUnitType string

const (
	BranchOrgUnitsUnitTypeHEADOFFICE       BranchOrgUnitsUnitType = "HEAD_OFFICE"
	BranchOrgUnitsUnitTypeBRANCH           BranchOrgUnitsUnitType = "BRANCH"
	BranchOrgUnitsUnitTypeREPOFFICE        BranchOrgUnitsUnitType = "REP_OFFICE"
	BranchOrgUnitsUnitTypeBUSINESSLOCATION BranchOrgUnitsUnitType = "BUSINESS_LOCATION"
	BranchOrgUnitsUnitTypeDEPARTMENT       BranchOrgUnitsUnitType = "DEPARTMENT"
)

func (e *BranchOrgUnitsUnitType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BranchOrgUnitsUnitType(s)
	case string:
		*e = BranchOrgUnitsUnitType(s)
	default:
		return fmt.Errorf("unsupported scan type for BranchOrgUnitsUnitType: %T", src)
	}
	return nil
}

type NullBranchOrgUnitsUnitType struct {
	BranchOrgUnitsUnitType BranchOrgUnitsUnitType `json:"branch_org_units_unit_type"`
	Valid                  bool                   `json:"valid"` // Valid is true if BranchOrgUnitsUnitType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBranchOrgUnitsUnitType) Scan(value interface{}) error {
	if value == nil {
		ns.BranchOrgUnitsUnitType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BranchOrgUnitsUnitType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBranchOrgUnitsUnitType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BranchOrgUnitsUnitType), nil
}

type CompanyProfileBusinessType string

const (
	CompanyProfileBusinessTypeTRADING    CompanyProfileBusinessType = "TRADING"
	CompanyProfileBusinessTypeSERVICE    CompanyProfileBusinessType = "SERVICE"
	CompanyProfileBusinessTypePRODUCTION CompanyProfileBusinessType = "PRODUCTION"
	CompanyProfileBusinessTypeMIXED      CompanyProfileBusinessType = "MIXED"
)

func (e *CompanyProfileBusinessType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompanyProfileBusinessType(s)
	case string:
		*e = CompanyProfileBusinessType(s)
	default:
		return fmt.Errorf("unsupported scan type for CompanyProfileBusinessType: %T", src)
	}
	return nil
}

type NullCompanyProfileBusinessType struct {
	CompanyProfileBusinessType CompanyProfileBusinessType `json:"company_profile_business_type"`
	Valid                      bool                       `json:"valid"` // Valid is true if CompanyProfileBusinessType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompanyProfileBusinessType) Scan(value interface{}) error {
	if value == nil {
		ns.CompanyProfileBusinessType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompanyProfileBusinessType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompanyProfileBusinessType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompanyProfileBusinessType), nil
}

type CompanyProfileCostingMethod string

const (
	CompanyProfileCostingMethodFIFO              CompanyProfileCostingMethod = "FIFO"
	CompanyProfileCostingMethodMOVINGWEIGHTEDAVG CompanyProfileCostingMethod = "MOVING_WEIGHTED_AVG"
	CompanyProfileCostingMethodPERIODICAVG       CompanyProfileCostingMethod = "PERIODIC_AVG"
)

func (e *CompanyProfileCostingMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompanyProfileCostingMethod(s)
	case string:
		*e = CompanyProfileCostingMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for CompanyProfileCostingMethod: %T", src)
	}
	return nil
}

type NullCompanyProfileCostingMethod struct {
	CompanyProfileCostingMethod CompanyProfileCostingMethod `json:"company_profile_costing_method"`
	Valid                       bool                        `json:"valid"` // Valid is true if CompanyProfileCostingMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompanyProfileCostingMethod) Scan(value interface{}) error {
	if value == nil {
		ns.CompanyProfileCostingMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompanyProfileCostingMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompanyProfileCostingMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompanyProfileCostingMethod), nil
}

type CompanyProfileRegime string

const (
	CompanyProfileRegimeTT1332016 CompanyProfileRegime = "TT133_2016"
	CompanyProfileRegimeTT992025  CompanyProfileRegime = "TT99_2025"
)

func (e *CompanyProfileRegime) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompanyProfileRegime(s)
	case string:
		*e = CompanyProfileRegime(s)
	default:
		return fmt.Errorf("unsupported scan type for CompanyProfileRegime: %T", src)
	}
	return nil
}

type NullCompanyProfileRegime struct {
	CompanyProfileRegime CompanyProfileRegime `json:"company_profile_regime"`
	Valid                bool                 `json:"valid"` // Valid is true if CompanyProfileRegime is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompanyProfileRegime) Scan(value interface{}) error {
	if value == nil {
		ns.CompanyProfileRegime, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompanyProfileRegime.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompanyProfileRegime) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompanyProfileRegime), nil
}

type CompanyProfileVatMethod string

const (
	CompanyProfileVatMethodDEDUCTION CompanyProfileVatMethod = "DEDUCTION"
	CompanyProfileVatMethodDIRECT    CompanyProfileVatMethod = "DIRECT"
)

func (e *CompanyProfileVatMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompanyProfileVatMethod(s)
	case string:
		*e = CompanyProfileVatMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for CompanyProfileVatMethod: %T", src)
	}
	return nil
}

type NullCompanyProfileVatMethod struct {
	CompanyProfileVatMethod CompanyProfileVatMethod `json:"company_profile_vat_method"`
	Valid                   bool                    `json:"valid"` // Valid is true if CompanyProfileVatMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompanyProfileVatMethod) Scan(value interface{}) error {
	if value == nil {
		ns.CompanyProfileVatMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompanyProfileVatMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompanyProfileVatMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompanyProfileVatMethod), nil
}

type UsersStatus string

const (
	UsersStatusPENDINGACTIVATION UsersStatus = "PENDING_ACTIVATION"
	UsersStatusACTIVE            UsersStatus = "ACTIVE"
	UsersStatusSUSPENDED         UsersStatus = "SUSPENDED"
	UsersStatusLOCKED            UsersStatus = "LOCKED"
	UsersStatusTERMINATED        UsersStatus = "TERMINATED"
)

func (e *UsersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersStatus(s)
	case string:
		*e = UsersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersStatus: %T", src)
	}
	return nil
}

type NullUsersStatus struct {
	UsersStatus UsersStatus `json:"users_status"`
	Valid       bool        `json:"valid"` // Valid is true if UsersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UsersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersStatus), nil
}

type VouchersVoucherType string

const (
	VouchersVoucherTypeSALES       VouchersVoucherType = "SALES"
	VouchersVoucherTypePURCHASE    VouchersVoucherType = "PURCHASE"
	VouchersVoucherTypeCASHRECEIPT VouchersVoucherType = "CASH_RECEIPT"
	VouchersVoucherTypeCASHPAYMENT VouchersVoucherType = "CASH_PAYMENT"
	VouchersVoucherTypeGENERAL     VouchersVoucherType = "GENERAL"
)

func (e *VouchersVoucherType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VouchersVoucherType(s)
	case string:
		*e = VouchersVoucherType(s)
	default:
		return fmt.Errorf("unsupported scan type for VouchersVoucherType: %T", src)
	}
	return nil
}

type NullVouchersVoucherType struct {
	VouchersVoucherType VouchersVoucherType `json:"vouchers_voucher_type"`
	Valid               bool                `json:"valid"` // Valid is true if VouchersVoucherType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVouchersVoucherType) Scan(value interface{}) error {
	if value == nil {
		ns.VouchersVoucherType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VouchersVoucherType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVouchersVoucherType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VouchersVoucherType), nil
}

type Account struct {
	ID          string              `json:"id"`
	Code        string              `json:"code"`
	Name        string              `json:"name"`
	ParentID    sql.NullString      `json:"parent_id"`
	AccountType AccountsAccountType `json:"account_type"`
	Nature      AccountsNature      `json:"nature"`
	IsActive    bool                `json:"is_active"`
	CreatedAt   time.Time           `json:"created_at"`
	UpdatedAt   time.Time           `json:"updated_at"`
}

type AccountingPeriod struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	IsClosed  bool      `json:"is_closed"`
	CreatedAt time.Time `json:"created_at"`
}

type BranchOrgUnit struct {
	ID                        string                             `json:"id"`
	ParentID                  sql.NullString                     `json:"parent_id"`
	CompanyProfileID          string                             `json:"company_profile_id"`
	Code                      string                             `json:"code"`
	Name                      string                             `json:"name"`
	UnitType                  BranchOrgUnitsUnitType             `json:"unit_type"`
	AccountingGovernance      BranchOrgUnitsAccountingGovernance `json:"accounting_governance"`
	TaxFilingMechanism        BranchOrgUnitsTaxFilingMechanism   `json:"tax_filing_mechanism"`
	TaxCode                   sql.NullString                     `json:"tax_code"`
	TaxAuthorityCode          sql.NullString                     `json:"tax_authority_code"`
	TaxAuthorityName          sql.NullString                     `json:"tax_authority_name"`
	ProvinceCityCode          string                             `json:"province_city_code"`
	Address                   string                             `json:"address"`
	ManagerName               sql.NullString                     `json:"manager_name"`
	ChiefAccountant           sql.NullString                     `json:"chief_accountant"`
	InternalReceivableAccount string                             `json:"internal_receivable_account"`
	InternalPayableAccount    string                             `json:"internal_payable_account"`
	HasOwnEinvoice            bool                               `json:"has_own_einvoice"`
	IsActive                  bool                               `json:"is_active"`
	CreatedAt                 time.Time                          `json:"created_at"`
	UpdatedAt                 time.Time                          `json:"updated_at"`
}

type CompanyProfile struct {
	ID                     string                      `json:"id"`
	TaxCode                string                      `json:"tax_code"`
	LegalName              string                      `json:"legal_name"`
	TradeName              sql.NullString              `json:"trade_name"`
	EnglishName            sql.NullString              `json:"english_name"`
	Address                string                      `json:"address"`
	ProvinceCity           sql.NullString              `json:"province_city"`
	DistrictWard           sql.NullString              `json:"district_ward"`
	Phone                  sql.NullString              `json:"phone"`
	Email                  sql.NullString              `json:"email"`
	Website                sql.NullString              `json:"website"`
	LegalRepresentative    string                      `json:"legal_representative"`
	RepresentativePosition sql.NullString              `json:"representative_position"`
	ChiefAccountant        string                      `json:"chief_accountant"`
	TaxAuthorityCode       string                      `json:"tax_authority_code"`
	TaxAuthorityName       string                      `json:"tax_authority_name"`
	StateBudgetChapter     sql.NullString              `json:"state_budget_chapter"`
	Regime                 CompanyProfileRegime        `json:"regime"`
	BaseCurrency           string                      `json:"base_currency"`
	FiscalYearStartMonth   int8                        `json:"fiscal_year_start_month"`
	VatMethod              CompanyProfileVatMethod     `json:"vat_method"`
	CostingMethod          CompanyProfileCostingMethod `json:"costing_method"`
	BusinessType           CompanyProfileBusinessType  `json:"business_type"`
	RegisteredBanks        json.RawMessage             `json:"registered_banks"`
	EinvoiceConfig         json.RawMessage             `json:"einvoice_config"`
	IsActive               bool                        `json:"is_active"`
	LockDate               sql.NullTime                `json:"lock_date"`
	CreatedAt              time.Time                   `json:"created_at"`
	UpdatedAt              time.Time                   `json:"updated_at"`
}

type Permission struct {
	ID          string         `json:"id"`
	Code        string         `json:"code"`
	Module      string         `json:"module"`
	Resource    string         `json:"resource"`
	Action      string         `json:"action"`
	Description sql.NullString `json:"description"`
}

type Role struct {
	ID          string         `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsSystem    bool           `json:"is_system"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type RolePermission struct {
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
}

type SodConflictRule struct {
	ID          string `json:"id"`
	RoleCodeA   string `json:"role_code_a"`
	RoleCodeB   string `json:"role_code_b"`
	LegalBasis  string `json:"legal_basis"`
	Description string `json:"description"`
}

type User struct {
	ID                     string         `json:"id"`
	CompanyProfileID       string         `json:"company_profile_id"`
	Username               string         `json:"username"`
	Email                  string         `json:"email"`
	PasswordHash           string         `json:"password_hash"`
	FullName               string         `json:"full_name"`
	Title                  sql.NullString `json:"title"`
	EmployeeCode           sql.NullString `json:"employee_code"`
	Status                 UsersStatus    `json:"status"`
	FailedLoginAttempts    int32          `json:"failed_login_attempts"`
	LockoutUntil           sql.NullTime   `json:"lockout_until"`
	PasswordChangedAt      time.Time      `json:"password_changed_at"`
	MustChangePasswordNext bool           `json:"must_change_password_next"`
	MfaSecret              sql.NullString `json:"mfa_secret"`
	IsMfaEnabled           bool           `json:"is_mfa_enabled"`
	DigitalCertSubject     sql.NullString `json:"digital_cert_subject"`
	DigitalCertSerial      sql.NullString `json:"digital_cert_serial"`
	LastLoginAt            sql.NullTime   `json:"last_login_at"`
	LastLoginIp            sql.NullString `json:"last_login_ip"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}

type UserOrgUnitScope struct {
	ID              string    `json:"id"`
	UserID          string    `json:"user_id"`
	OrgUnitID       string    `json:"org_unit_id"`
	IsDefault       bool      `json:"is_default"`
	IncludeChildren bool      `json:"include_children"`
	CreatedAt       time.Time `json:"created_at"`
}

type UserRole struct {
	UserID     string         `json:"user_id"`
	RoleID     string         `json:"role_id"`
	AssignedAt time.Time      `json:"assigned_at"`
	AssignedBy sql.NullString `json:"assigned_by"`
}

type Voucher struct {
	ID          string              `json:"id"`
	VoucherNo   string              `json:"voucher_no"`
	VoucherDate time.Time           `json:"voucher_date"`
	PostedDate  time.Time           `json:"posted_date"`
	VoucherType VouchersVoucherType `json:"voucher_type"`
	Description sql.NullString      `json:"description"`
	IsPosted    bool                `json:"is_posted"`
	CreatedAt   time.Time           `json:"created_at"`
}

type VoucherLine struct {
	ID              string         `json:"id"`
	VoucherID       string         `json:"voucher_id"`
	LineOrder       int32          `json:"line_order"`
	DebitAccountID  string         `json:"debit_account_id"`
	CreditAccountID string         `json:"credit_account_id"`
	Amount          string         `json:"amount"`
	Note            sql.NullString `json:"note"`
}
