// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: opening.sql

package mariadb

import (
	"context"
	"database/sql"
	"time"
)

const createOpeningBatch = `-- name: CreateOpeningBatch :exec
INSERT INTO opening_batches (
    id, company_profile_id, as_of_date, status, total_debit, total_credit, notes, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOpeningBatchParams struct {
	ID               string               `json:"id"`
	CompanyProfileID string               `json:"company_profile_id"`
	AsOfDate         time.Time            `json:"as_of_date"`
	Status           OpeningBatchesStatus `json:"status"`
	TotalDebit       string               `json:"total_debit"`
	TotalCredit      string               `json:"total_credit"`
	Notes            sql.NullString       `json:"notes"`
	CreatedAt        time.Time            `json:"created_at"`
	UpdatedAt        time.Time            `json:"updated_at"`
}

func (q *Queries) CreateOpeningBatch(ctx context.Context, arg CreateOpeningBatchParams) error {
	_, err := q.db.ExecContext(ctx, createOpeningBatch,
		arg.ID,
		arg.CompanyProfileID,
		arg.AsOfDate,
		arg.Status,
		arg.TotalDebit,
		arg.TotalCredit,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAccountBalancesByBatch = `-- name: DeleteAccountBalancesByBatch :exec
DELETE FROM account_opening_balances WHERE batch_id = ?
`

func (q *Queries) DeleteAccountBalancesByBatch(ctx context.Context, batchID string) error {
	_, err := q.db.ExecContext(ctx, deleteAccountBalancesByBatch, batchID)
	return err
}

const deleteAssetBalancesByBatch = `-- name: DeleteAssetBalancesByBatch :exec
DELETE FROM asset_opening_balances WHERE batch_id = ?
`

func (q *Queries) DeleteAssetBalancesByBatch(ctx context.Context, batchID string) error {
	_, err := q.db.ExecContext(ctx, deleteAssetBalancesByBatch, batchID)
	return err
}

const deleteCustomerBalancesByBatch = `-- name: DeleteCustomerBalancesByBatch :exec
DELETE FROM customer_opening_balances WHERE batch_id = ?
`

func (q *Queries) DeleteCustomerBalancesByBatch(ctx context.Context, batchID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerBalancesByBatch, batchID)
	return err
}

const deleteInventoryBalancesByBatch = `-- name: DeleteInventoryBalancesByBatch :exec
DELETE FROM inventory_opening_balances WHERE batch_id = ?
`

func (q *Queries) DeleteInventoryBalancesByBatch(ctx context.Context, batchID string) error {
	_, err := q.db.ExecContext(ctx, deleteInventoryBalancesByBatch, batchID)
	return err
}

const deleteVendorBalancesByBatch = `-- name: DeleteVendorBalancesByBatch :exec
DELETE FROM vendor_opening_balances WHERE batch_id = ?
`

func (q *Queries) DeleteVendorBalancesByBatch(ctx context.Context, batchID string) error {
	_, err := q.db.ExecContext(ctx, deleteVendorBalancesByBatch, batchID)
	return err
}

const getOpeningBatchByDate = `-- name: GetOpeningBatchByDate :one
SELECT id, company_profile_id, as_of_date, status, total_debit, total_credit, committed_at, committed_by, notes, created_at, updated_at FROM opening_batches 
WHERE company_profile_id = ? AND as_of_date = ? 
LIMIT 1
`

type GetOpeningBatchByDateParams struct {
	CompanyProfileID string    `json:"company_profile_id"`
	AsOfDate         time.Time `json:"as_of_date"`
}

func (q *Queries) GetOpeningBatchByDate(ctx context.Context, arg GetOpeningBatchByDateParams) (OpeningBatch, error) {
	row := q.db.QueryRowContext(ctx, getOpeningBatchByDate, arg.CompanyProfileID, arg.AsOfDate)
	var i OpeningBatch
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.AsOfDate,
		&i.Status,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.CommittedAt,
		&i.CommittedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpeningBatchByID = `-- name: GetOpeningBatchByID :one
SELECT id, company_profile_id, as_of_date, status, total_debit, total_credit, committed_at, committed_by, notes, created_at, updated_at FROM opening_batches WHERE id = ? LIMIT 1
`

func (q *Queries) GetOpeningBatchByID(ctx context.Context, id string) (OpeningBatch, error) {
	row := q.db.QueryRowContext(ctx, getOpeningBatchByID, id)
	var i OpeningBatch
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.AsOfDate,
		&i.Status,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.CommittedAt,
		&i.CommittedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAccountBalance = `-- name: InsertAccountBalance :exec
INSERT INTO account_opening_balances (
    id, batch_id, account_id, currency_code, debit_amount_fc, credit_amount_fc,
    exchange_rate, debit_amount_vnd, credit_amount_vnd, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAccountBalanceParams struct {
	ID              string    `json:"id"`
	BatchID         string    `json:"batch_id"`
	AccountID       string    `json:"account_id"`
	CurrencyCode    string    `json:"currency_code"`
	DebitAmountFc   string    `json:"debit_amount_fc"`
	CreditAmountFc  string    `json:"credit_amount_fc"`
	ExchangeRate    string    `json:"exchange_rate"`
	DebitAmountVnd  string    `json:"debit_amount_vnd"`
	CreditAmountVnd string    `json:"credit_amount_vnd"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) InsertAccountBalance(ctx context.Context, arg InsertAccountBalanceParams) error {
	_, err := q.db.ExecContext(ctx, insertAccountBalance,
		arg.ID,
		arg.BatchID,
		arg.AccountID,
		arg.CurrencyCode,
		arg.DebitAmountFc,
		arg.CreditAmountFc,
		arg.ExchangeRate,
		arg.DebitAmountVnd,
		arg.CreditAmountVnd,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertAssetBalance = `-- name: InsertAssetBalance :exec
INSERT INTO asset_opening_balances (
    id, batch_id, asset_code, asset_name, asset_account_id, depreciation_account_id,
    cost_account_id, department_id, acquisition_date, start_depreciation_date,
    original_cost, accumulated_depreciation, net_book_value, useful_life_months,
    remaining_life_months, monthly_depreciation, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAssetBalanceParams struct {
	ID                      string         `json:"id"`
	BatchID                 string         `json:"batch_id"`
	AssetCode               string         `json:"asset_code"`
	AssetName               string         `json:"asset_name"`
	AssetAccountID          string         `json:"asset_account_id"`
	DepreciationAccountID   string         `json:"depreciation_account_id"`
	CostAccountID           string         `json:"cost_account_id"`
	DepartmentID            sql.NullString `json:"department_id"`
	AcquisitionDate         time.Time      `json:"acquisition_date"`
	StartDepreciationDate   time.Time      `json:"start_depreciation_date"`
	OriginalCost            string         `json:"original_cost"`
	AccumulatedDepreciation string         `json:"accumulated_depreciation"`
	NetBookValue            string         `json:"net_book_value"`
	UsefulLifeMonths        int32          `json:"useful_life_months"`
	RemainingLifeMonths     int32          `json:"remaining_life_months"`
	MonthlyDepreciation     string         `json:"monthly_depreciation"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
}

func (q *Queries) InsertAssetBalance(ctx context.Context, arg InsertAssetBalanceParams) error {
	_, err := q.db.ExecContext(ctx, insertAssetBalance,
		arg.ID,
		arg.BatchID,
		arg.AssetCode,
		arg.AssetName,
		arg.AssetAccountID,
		arg.DepreciationAccountID,
		arg.CostAccountID,
		arg.DepartmentID,
		arg.AcquisitionDate,
		arg.StartDepreciationDate,
		arg.OriginalCost,
		arg.AccumulatedDepreciation,
		arg.NetBookValue,
		arg.UsefulLifeMonths,
		arg.RemainingLifeMonths,
		arg.MonthlyDepreciation,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertCustomerBalance = `-- name: InsertCustomerBalance :exec
INSERT INTO customer_opening_balances (
    id, batch_id, customer_id, invoice_no, invoice_date, due_date, currency_code,
    debit_amount_fc, credit_amount_fc, exchange_rate, debit_amount_vnd, credit_amount_vnd,
    notes, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCustomerBalanceParams struct {
	ID              string         `json:"id"`
	BatchID         string         `json:"batch_id"`
	CustomerID      string         `json:"customer_id"`
	InvoiceNo       sql.NullString `json:"invoice_no"`
	InvoiceDate     sql.NullTime   `json:"invoice_date"`
	DueDate         sql.NullTime   `json:"due_date"`
	CurrencyCode    string         `json:"currency_code"`
	DebitAmountFc   string         `json:"debit_amount_fc"`
	CreditAmountFc  string         `json:"credit_amount_fc"`
	ExchangeRate    string         `json:"exchange_rate"`
	DebitAmountVnd  string         `json:"debit_amount_vnd"`
	CreditAmountVnd string         `json:"credit_amount_vnd"`
	Notes           sql.NullString `json:"notes"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) InsertCustomerBalance(ctx context.Context, arg InsertCustomerBalanceParams) error {
	_, err := q.db.ExecContext(ctx, insertCustomerBalance,
		arg.ID,
		arg.BatchID,
		arg.CustomerID,
		arg.InvoiceNo,
		arg.InvoiceDate,
		arg.DueDate,
		arg.CurrencyCode,
		arg.DebitAmountFc,
		arg.CreditAmountFc,
		arg.ExchangeRate,
		arg.DebitAmountVnd,
		arg.CreditAmountVnd,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertInventoryBalance = `-- name: InsertInventoryBalance :exec
INSERT INTO inventory_opening_balances (
    id, batch_id, warehouse_id, item_id, uom_id, quantity, unit_cost, total_amount_vnd,
    batch_number, expiry_date, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertInventoryBalanceParams struct {
	ID             string         `json:"id"`
	BatchID        string         `json:"batch_id"`
	WarehouseID    string         `json:"warehouse_id"`
	ItemID         string         `json:"item_id"`
	UomID          string         `json:"uom_id"`
	Quantity       string         `json:"quantity"`
	UnitCost       string         `json:"unit_cost"`
	TotalAmountVnd string         `json:"total_amount_vnd"`
	BatchNumber    sql.NullString `json:"batch_number"`
	ExpiryDate     sql.NullTime   `json:"expiry_date"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) InsertInventoryBalance(ctx context.Context, arg InsertInventoryBalanceParams) error {
	_, err := q.db.ExecContext(ctx, insertInventoryBalance,
		arg.ID,
		arg.BatchID,
		arg.WarehouseID,
		arg.ItemID,
		arg.UomID,
		arg.Quantity,
		arg.UnitCost,
		arg.TotalAmountVnd,
		arg.BatchNumber,
		arg.ExpiryDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertVendorBalance = `-- name: InsertVendorBalance :exec
INSERT INTO vendor_opening_balances (
    id, batch_id, vendor_id, bill_no, bill_date, due_date, currency_code,
    debit_amount_fc, credit_amount_fc, exchange_rate, debit_amount_vnd, credit_amount_vnd,
    notes, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertVendorBalanceParams struct {
	ID              string         `json:"id"`
	BatchID         string         `json:"batch_id"`
	VendorID        string         `json:"vendor_id"`
	BillNo          sql.NullString `json:"bill_no"`
	BillDate        sql.NullTime   `json:"bill_date"`
	DueDate         sql.NullTime   `json:"due_date"`
	CurrencyCode    string         `json:"currency_code"`
	DebitAmountFc   string         `json:"debit_amount_fc"`
	CreditAmountFc  string         `json:"credit_amount_fc"`
	ExchangeRate    string         `json:"exchange_rate"`
	DebitAmountVnd  string         `json:"debit_amount_vnd"`
	CreditAmountVnd string         `json:"credit_amount_vnd"`
	Notes           sql.NullString `json:"notes"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) InsertVendorBalance(ctx context.Context, arg InsertVendorBalanceParams) error {
	_, err := q.db.ExecContext(ctx, insertVendorBalance,
		arg.ID,
		arg.BatchID,
		arg.VendorID,
		arg.BillNo,
		arg.BillDate,
		arg.DueDate,
		arg.CurrencyCode,
		arg.DebitAmountFc,
		arg.CreditAmountFc,
		arg.ExchangeRate,
		arg.DebitAmountVnd,
		arg.CreditAmountVnd,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listAccountBalancesByBatch = `-- name: ListAccountBalancesByBatch :many
SELECT aob.id, aob.batch_id, aob.account_id, aob.currency_code, aob.debit_amount_fc, aob.credit_amount_fc, aob.exchange_rate, aob.debit_amount_vnd, aob.credit_amount_vnd, aob.created_at, aob.updated_at, a.code as account_code, a.name as account_name
FROM account_opening_balances aob
JOIN accounts a ON aob.account_id = a.id
WHERE aob.batch_id = ?
ORDER BY a.code ASC
`

type ListAccountBalancesByBatchRow struct {
	ID              string    `json:"id"`
	BatchID         string    `json:"batch_id"`
	AccountID       string    `json:"account_id"`
	CurrencyCode    string    `json:"currency_code"`
	DebitAmountFc   string    `json:"debit_amount_fc"`
	CreditAmountFc  string    `json:"credit_amount_fc"`
	ExchangeRate    string    `json:"exchange_rate"`
	DebitAmountVnd  string    `json:"debit_amount_vnd"`
	CreditAmountVnd string    `json:"credit_amount_vnd"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	AccountCode     string    `json:"account_code"`
	AccountName     string    `json:"account_name"`
}

func (q *Queries) ListAccountBalancesByBatch(ctx context.Context, batchID string) ([]ListAccountBalancesByBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountBalancesByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountBalancesByBatchRow
	for rows.Next() {
		var i ListAccountBalancesByBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.AccountID,
			&i.CurrencyCode,
			&i.DebitAmountFc,
			&i.CreditAmountFc,
			&i.ExchangeRate,
			&i.DebitAmountVnd,
			&i.CreditAmountVnd,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountCode,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetBalancesByBatch = `-- name: ListAssetBalancesByBatch :many
SELECT aob.id, aob.batch_id, aob.asset_code, aob.asset_name, aob.asset_account_id, aob.depreciation_account_id, aob.cost_account_id, aob.department_id, aob.acquisition_date, aob.start_depreciation_date, aob.original_cost, aob.accumulated_depreciation, aob.net_book_value, aob.useful_life_months, aob.remaining_life_months, aob.monthly_depreciation, aob.created_at, aob.updated_at, aa.code as asset_account_code, da.code as depreciation_account_code, ca.code as cost_account_code
FROM asset_opening_balances aob
JOIN accounts aa ON aob.asset_account_id = aa.id
JOIN accounts da ON aob.depreciation_account_id = da.id
JOIN accounts ca ON aob.cost_account_id = ca.id
WHERE aob.batch_id = ?
ORDER BY aob.asset_code ASC
`

type ListAssetBalancesByBatchRow struct {
	ID                      string         `json:"id"`
	BatchID                 string         `json:"batch_id"`
	AssetCode               string         `json:"asset_code"`
	AssetName               string         `json:"asset_name"`
	AssetAccountID          string         `json:"asset_account_id"`
	DepreciationAccountID   string         `json:"depreciation_account_id"`
	CostAccountID           string         `json:"cost_account_id"`
	DepartmentID            sql.NullString `json:"department_id"`
	AcquisitionDate         time.Time      `json:"acquisition_date"`
	StartDepreciationDate   time.Time      `json:"start_depreciation_date"`
	OriginalCost            string         `json:"original_cost"`
	AccumulatedDepreciation string         `json:"accumulated_depreciation"`
	NetBookValue            string         `json:"net_book_value"`
	UsefulLifeMonths        int32          `json:"useful_life_months"`
	RemainingLifeMonths     int32          `json:"remaining_life_months"`
	MonthlyDepreciation     string         `json:"monthly_depreciation"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
	AssetAccountCode        string         `json:"asset_account_code"`
	DepreciationAccountCode string         `json:"depreciation_account_code"`
	CostAccountCode         string         `json:"cost_account_code"`
}

func (q *Queries) ListAssetBalancesByBatch(ctx context.Context, batchID string) ([]ListAssetBalancesByBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetBalancesByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetBalancesByBatchRow
	for rows.Next() {
		var i ListAssetBalancesByBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.AssetCode,
			&i.AssetName,
			&i.AssetAccountID,
			&i.DepreciationAccountID,
			&i.CostAccountID,
			&i.DepartmentID,
			&i.AcquisitionDate,
			&i.StartDepreciationDate,
			&i.OriginalCost,
			&i.AccumulatedDepreciation,
			&i.NetBookValue,
			&i.UsefulLifeMonths,
			&i.RemainingLifeMonths,
			&i.MonthlyDepreciation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssetAccountCode,
			&i.DepreciationAccountCode,
			&i.CostAccountCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerBalancesByBatch = `-- name: ListCustomerBalancesByBatch :many
SELECT cob.id, cob.batch_id, cob.customer_id, cob.invoice_no, cob.invoice_date, cob.due_date, cob.currency_code, cob.debit_amount_fc, cob.credit_amount_fc, cob.exchange_rate, cob.debit_amount_vnd, cob.credit_amount_vnd, cob.notes, cob.created_at, cob.updated_at, c.code as customer_code, c.name as customer_name
FROM customer_opening_balances cob
JOIN customers c ON cob.customer_id = c.id
WHERE cob.batch_id = ?
ORDER BY c.code ASC
`

type ListCustomerBalancesByBatchRow struct {
	ID              string         `json:"id"`
	BatchID         string         `json:"batch_id"`
	CustomerID      string         `json:"customer_id"`
	InvoiceNo       sql.NullString `json:"invoice_no"`
	InvoiceDate     sql.NullTime   `json:"invoice_date"`
	DueDate         sql.NullTime   `json:"due_date"`
	CurrencyCode    string         `json:"currency_code"`
	DebitAmountFc   string         `json:"debit_amount_fc"`
	CreditAmountFc  string         `json:"credit_amount_fc"`
	ExchangeRate    string         `json:"exchange_rate"`
	DebitAmountVnd  string         `json:"debit_amount_vnd"`
	CreditAmountVnd string         `json:"credit_amount_vnd"`
	Notes           sql.NullString `json:"notes"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	CustomerCode    string         `json:"customer_code"`
	CustomerName    string         `json:"customer_name"`
}

func (q *Queries) ListCustomerBalancesByBatch(ctx context.Context, batchID string) ([]ListCustomerBalancesByBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, listCustomerBalancesByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerBalancesByBatchRow
	for rows.Next() {
		var i ListCustomerBalancesByBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.CustomerID,
			&i.InvoiceNo,
			&i.InvoiceDate,
			&i.DueDate,
			&i.CurrencyCode,
			&i.DebitAmountFc,
			&i.CreditAmountFc,
			&i.ExchangeRate,
			&i.DebitAmountVnd,
			&i.CreditAmountVnd,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerCode,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryBalancesByBatch = `-- name: ListInventoryBalancesByBatch :many
SELECT iob.id, iob.batch_id, iob.warehouse_id, iob.item_id, iob.uom_id, iob.quantity, iob.unit_cost, iob.total_amount_vnd, iob.batch_number, iob.expiry_date, iob.created_at, iob.updated_at, w.code as warehouse_code, w.name as warehouse_name,
       i.code as item_code, i.name as item_name, u.code as uom_code
FROM inventory_opening_balances iob
JOIN warehouses w ON iob.warehouse_id = w.id
JOIN items i ON iob.item_id = i.id
JOIN unit_of_measures u ON iob.uom_id = u.id
WHERE iob.batch_id = ?
ORDER BY w.code, i.code ASC
`

type ListInventoryBalancesByBatchRow struct {
	ID             string         `json:"id"`
	BatchID        string         `json:"batch_id"`
	WarehouseID    string         `json:"warehouse_id"`
	ItemID         string         `json:"item_id"`
	UomID          string         `json:"uom_id"`
	Quantity       string         `json:"quantity"`
	UnitCost       string         `json:"unit_cost"`
	TotalAmountVnd string         `json:"total_amount_vnd"`
	BatchNumber    sql.NullString `json:"batch_number"`
	ExpiryDate     sql.NullTime   `json:"expiry_date"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	WarehouseCode  string         `json:"warehouse_code"`
	WarehouseName  string         `json:"warehouse_name"`
	ItemCode       string         `json:"item_code"`
	ItemName       string         `json:"item_name"`
	UomCode        string         `json:"uom_code"`
}

func (q *Queries) ListInventoryBalancesByBatch(ctx context.Context, batchID string) ([]ListInventoryBalancesByBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, listInventoryBalancesByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryBalancesByBatchRow
	for rows.Next() {
		var i ListInventoryBalancesByBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.WarehouseID,
			&i.ItemID,
			&i.UomID,
			&i.Quantity,
			&i.UnitCost,
			&i.TotalAmountVnd,
			&i.BatchNumber,
			&i.ExpiryDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WarehouseCode,
			&i.WarehouseName,
			&i.ItemCode,
			&i.ItemName,
			&i.UomCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorBalancesByBatch = `-- name: ListVendorBalancesByBatch :many
SELECT vob.id, vob.batch_id, vob.vendor_id, vob.bill_no, vob.bill_date, vob.due_date, vob.currency_code, vob.debit_amount_fc, vob.credit_amount_fc, vob.exchange_rate, vob.debit_amount_vnd, vob.credit_amount_vnd, vob.notes, vob.created_at, vob.updated_at, v.code as vendor_code, v.name as vendor_name
FROM vendor_opening_balances vob
JOIN vendors v ON vob.vendor_id = v.id
WHERE vob.batch_id = ?
ORDER BY v.code ASC
`

type ListVendorBalancesByBatchRow struct {
	ID              string         `json:"id"`
	BatchID         string         `json:"batch_id"`
	VendorID        string         `json:"vendor_id"`
	BillNo          sql.NullString `json:"bill_no"`
	BillDate        sql.NullTime   `json:"bill_date"`
	DueDate         sql.NullTime   `json:"due_date"`
	CurrencyCode    string         `json:"currency_code"`
	DebitAmountFc   string         `json:"debit_amount_fc"`
	CreditAmountFc  string         `json:"credit_amount_fc"`
	ExchangeRate    string         `json:"exchange_rate"`
	DebitAmountVnd  string         `json:"debit_amount_vnd"`
	CreditAmountVnd string         `json:"credit_amount_vnd"`
	Notes           sql.NullString `json:"notes"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	VendorCode      string         `json:"vendor_code"`
	VendorName      string         `json:"vendor_name"`
}

func (q *Queries) ListVendorBalancesByBatch(ctx context.Context, batchID string) ([]ListVendorBalancesByBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, listVendorBalancesByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVendorBalancesByBatchRow
	for rows.Next() {
		var i ListVendorBalancesByBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.VendorID,
			&i.BillNo,
			&i.BillDate,
			&i.DueDate,
			&i.CurrencyCode,
			&i.DebitAmountFc,
			&i.CreditAmountFc,
			&i.ExchangeRate,
			&i.DebitAmountVnd,
			&i.CreditAmountVnd,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VendorCode,
			&i.VendorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOpeningBatchStatus = `-- name: UpdateOpeningBatchStatus :exec
UPDATE opening_batches 
SET status = ?, committed_at = ?, committed_by = ?, updated_at = ?
WHERE id = ?
`

type UpdateOpeningBatchStatusParams struct {
	Status      OpeningBatchesStatus `json:"status"`
	CommittedAt sql.NullTime         `json:"committed_at"`
	CommittedBy sql.NullString       `json:"committed_by"`
	UpdatedAt   time.Time            `json:"updated_at"`
	ID          string               `json:"id"`
}

func (q *Queries) UpdateOpeningBatchStatus(ctx context.Context, arg UpdateOpeningBatchStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOpeningBatchStatus,
		arg.Status,
		arg.CommittedAt,
		arg.CommittedBy,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateOpeningBatchTotals = `-- name: UpdateOpeningBatchTotals :exec
UPDATE opening_batches 
SET total_debit = ?, total_credit = ?, updated_at = ?
WHERE id = ?
`

type UpdateOpeningBatchTotalsParams struct {
	TotalDebit  string    `json:"total_debit"`
	TotalCredit string    `json:"total_credit"`
	UpdatedAt   time.Time `json:"updated_at"`
	ID          string    `json:"id"`
}

func (q *Queries) UpdateOpeningBatchTotals(ctx context.Context, arg UpdateOpeningBatchTotalsParams) error {
	_, err := q.db.ExecContext(ctx, updateOpeningBatchTotals,
		arg.TotalDebit,
		arg.TotalCredit,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
