// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org_unit.sql

package mariadb

import (
	"context"
	"database/sql"
)

const createBranchOrgUnit = `-- name: CreateBranchOrgUnit :exec
INSERT INTO branch_org_units (
    id, parent_id, company_profile_id, code, name, unit_type,
    accounting_governance, tax_filing_mechanism, tax_code, tax_authority_code,
    tax_authority_name, province_city_code, address, manager_name,
    chief_accountant, internal_receivable_account, internal_payable_account,
    has_own_einvoice, is_active
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?
)
`

type CreateBranchOrgUnitParams struct {
	ID                        string                             `json:"id"`
	ParentID                  sql.NullString                     `json:"parent_id"`
	CompanyProfileID          string                             `json:"company_profile_id"`
	Code                      string                             `json:"code"`
	Name                      string                             `json:"name"`
	UnitType                  BranchOrgUnitsUnitType             `json:"unit_type"`
	AccountingGovernance      BranchOrgUnitsAccountingGovernance `json:"accounting_governance"`
	TaxFilingMechanism        BranchOrgUnitsTaxFilingMechanism   `json:"tax_filing_mechanism"`
	TaxCode                   sql.NullString                     `json:"tax_code"`
	TaxAuthorityCode          sql.NullString                     `json:"tax_authority_code"`
	TaxAuthorityName          sql.NullString                     `json:"tax_authority_name"`
	ProvinceCityCode          string                             `json:"province_city_code"`
	Address                   string                             `json:"address"`
	ManagerName               sql.NullString                     `json:"manager_name"`
	ChiefAccountant           sql.NullString                     `json:"chief_accountant"`
	InternalReceivableAccount string                             `json:"internal_receivable_account"`
	InternalPayableAccount    string                             `json:"internal_payable_account"`
	HasOwnEinvoice            bool                               `json:"has_own_einvoice"`
	IsActive                  bool                               `json:"is_active"`
}

func (q *Queries) CreateBranchOrgUnit(ctx context.Context, arg CreateBranchOrgUnitParams) error {
	_, err := q.db.ExecContext(ctx, createBranchOrgUnit,
		arg.ID,
		arg.ParentID,
		arg.CompanyProfileID,
		arg.Code,
		arg.Name,
		arg.UnitType,
		arg.AccountingGovernance,
		arg.TaxFilingMechanism,
		arg.TaxCode,
		arg.TaxAuthorityCode,
		arg.TaxAuthorityName,
		arg.ProvinceCityCode,
		arg.Address,
		arg.ManagerName,
		arg.ChiefAccountant,
		arg.InternalReceivableAccount,
		arg.InternalPayableAccount,
		arg.HasOwnEinvoice,
		arg.IsActive,
	)
	return err
}

const getBranchOrgUnitByCode = `-- name: GetBranchOrgUnitByCode :one
SELECT id, parent_id, company_profile_id, code, name, unit_type,
       accounting_governance, tax_filing_mechanism, tax_code, tax_authority_code,
       tax_authority_name, province_city_code, address, manager_name,
       chief_accountant, internal_receivable_account, internal_payable_account,
       has_own_einvoice, is_active, created_at, updated_at
FROM branch_org_units
WHERE company_profile_id = ? AND code = ?
LIMIT 1
`

type GetBranchOrgUnitByCodeParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	Code             string `json:"code"`
}

func (q *Queries) GetBranchOrgUnitByCode(ctx context.Context, arg GetBranchOrgUnitByCodeParams) (BranchOrgUnit, error) {
	row := q.db.QueryRowContext(ctx, getBranchOrgUnitByCode, arg.CompanyProfileID, arg.Code)
	var i BranchOrgUnit
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.CompanyProfileID,
		&i.Code,
		&i.Name,
		&i.UnitType,
		&i.AccountingGovernance,
		&i.TaxFilingMechanism,
		&i.TaxCode,
		&i.TaxAuthorityCode,
		&i.TaxAuthorityName,
		&i.ProvinceCityCode,
		&i.Address,
		&i.ManagerName,
		&i.ChiefAccountant,
		&i.InternalReceivableAccount,
		&i.InternalPayableAccount,
		&i.HasOwnEinvoice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBranchOrgUnitByID = `-- name: GetBranchOrgUnitByID :one
SELECT id, parent_id, company_profile_id, code, name, unit_type,
       accounting_governance, tax_filing_mechanism, tax_code, tax_authority_code,
       tax_authority_name, province_city_code, address, manager_name,
       chief_accountant, internal_receivable_account, internal_payable_account,
       has_own_einvoice, is_active, created_at, updated_at
FROM branch_org_units
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetBranchOrgUnitByID(ctx context.Context, id string) (BranchOrgUnit, error) {
	row := q.db.QueryRowContext(ctx, getBranchOrgUnitByID, id)
	var i BranchOrgUnit
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.CompanyProfileID,
		&i.Code,
		&i.Name,
		&i.UnitType,
		&i.AccountingGovernance,
		&i.TaxFilingMechanism,
		&i.TaxCode,
		&i.TaxAuthorityCode,
		&i.TaxAuthorityName,
		&i.ProvinceCityCode,
		&i.Address,
		&i.ManagerName,
		&i.ChiefAccountant,
		&i.InternalReceivableAccount,
		&i.InternalPayableAccount,
		&i.HasOwnEinvoice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBranchOrgUnitsByCompany = `-- name: ListBranchOrgUnitsByCompany :many
SELECT id, parent_id, company_profile_id, code, name, unit_type,
       accounting_governance, tax_filing_mechanism, tax_code, tax_authority_code,
       tax_authority_name, province_city_code, address, manager_name,
       chief_accountant, internal_receivable_account, internal_payable_account,
       has_own_einvoice, is_active, created_at, updated_at
FROM branch_org_units
WHERE company_profile_id = ? AND is_active = TRUE
ORDER BY code ASC
`

func (q *Queries) ListBranchOrgUnitsByCompany(ctx context.Context, companyProfileID string) ([]BranchOrgUnit, error) {
	rows, err := q.db.QueryContext(ctx, listBranchOrgUnitsByCompany, companyProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BranchOrgUnit
	for rows.Next() {
		var i BranchOrgUnit
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.CompanyProfileID,
			&i.Code,
			&i.Name,
			&i.UnitType,
			&i.AccountingGovernance,
			&i.TaxFilingMechanism,
			&i.TaxCode,
			&i.TaxAuthorityCode,
			&i.TaxAuthorityName,
			&i.ProvinceCityCode,
			&i.Address,
			&i.ManagerName,
			&i.ChiefAccountant,
			&i.InternalReceivableAccount,
			&i.InternalPayableAccount,
			&i.HasOwnEinvoice,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranchOrgUnit = `-- name: UpdateBranchOrgUnit :exec
UPDATE branch_org_units
SET name = ?,
    accounting_governance = ?,
    tax_filing_mechanism = ?,
    tax_code = ?,
    tax_authority_code = ?,
    tax_authority_name = ?,
    province_city_code = ?,
    address = ?,
    manager_name = ?,
    chief_accountant = ?,
    internal_receivable_account = ?,
    internal_payable_account = ?,
    has_own_einvoice = ?,
    is_active = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateBranchOrgUnitParams struct {
	Name                      string                             `json:"name"`
	AccountingGovernance      BranchOrgUnitsAccountingGovernance `json:"accounting_governance"`
	TaxFilingMechanism        BranchOrgUnitsTaxFilingMechanism   `json:"tax_filing_mechanism"`
	TaxCode                   sql.NullString                     `json:"tax_code"`
	TaxAuthorityCode          sql.NullString                     `json:"tax_authority_code"`
	TaxAuthorityName          sql.NullString                     `json:"tax_authority_name"`
	ProvinceCityCode          string                             `json:"province_city_code"`
	Address                   string                             `json:"address"`
	ManagerName               sql.NullString                     `json:"manager_name"`
	ChiefAccountant           sql.NullString                     `json:"chief_accountant"`
	InternalReceivableAccount string                             `json:"internal_receivable_account"`
	InternalPayableAccount    string                             `json:"internal_payable_account"`
	HasOwnEinvoice            bool                               `json:"has_own_einvoice"`
	IsActive                  bool                               `json:"is_active"`
	ID                        string                             `json:"id"`
}

func (q *Queries) UpdateBranchOrgUnit(ctx context.Context, arg UpdateBranchOrgUnitParams) error {
	_, err := q.db.ExecContext(ctx, updateBranchOrgUnit,
		arg.Name,
		arg.AccountingGovernance,
		arg.TaxFilingMechanism,
		arg.TaxCode,
		arg.TaxAuthorityCode,
		arg.TaxAuthorityName,
		arg.ProvinceCityCode,
		arg.Address,
		arg.ManagerName,
		arg.ChiefAccountant,
		arg.InternalReceivableAccount,
		arg.InternalPayableAccount,
		arg.HasOwnEinvoice,
		arg.IsActive,
		arg.ID,
	)
	return err
}
