// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purchase.sql

package mariadb

import (
	"context"
	"database/sql"
	"time"
)

const createPurchaseInvoice = `-- name: CreatePurchaseInvoice :exec
INSERT INTO purchase_invoices (
    id,
    voucher_id,
    company_profile_id,
    vendor_id,
    invoice_template,
    invoice_series,
    invoice_no,
    invoice_date,
    due_date,
    payment_status,
    subtotal_vnd,
    vat_amount_vnd,
    total_amount_vnd,
    paid_amount_vnd,
    is_stock_inward_auto
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreatePurchaseInvoiceParams struct {
	ID                string                        `json:"id"`
	VoucherID         string                        `json:"voucher_id"`
	CompanyProfileID  string                        `json:"company_profile_id"`
	VendorID          string                        `json:"vendor_id"`
	InvoiceTemplate   string                        `json:"invoice_template"`
	InvoiceSeries     string                        `json:"invoice_series"`
	InvoiceNo         string                        `json:"invoice_no"`
	InvoiceDate       time.Time                     `json:"invoice_date"`
	DueDate           time.Time                     `json:"due_date"`
	PaymentStatus     PurchaseInvoicesPaymentStatus `json:"payment_status"`
	SubtotalVnd       string                        `json:"subtotal_vnd"`
	VatAmountVnd      string                        `json:"vat_amount_vnd"`
	TotalAmountVnd    string                        `json:"total_amount_vnd"`
	PaidAmountVnd     string                        `json:"paid_amount_vnd"`
	IsStockInwardAuto bool                          `json:"is_stock_inward_auto"`
}

func (q *Queries) CreatePurchaseInvoice(ctx context.Context, arg CreatePurchaseInvoiceParams) error {
	_, err := q.db.ExecContext(ctx, createPurchaseInvoice,
		arg.ID,
		arg.VoucherID,
		arg.CompanyProfileID,
		arg.VendorID,
		arg.InvoiceTemplate,
		arg.InvoiceSeries,
		arg.InvoiceNo,
		arg.InvoiceDate,
		arg.DueDate,
		arg.PaymentStatus,
		arg.SubtotalVnd,
		arg.VatAmountVnd,
		arg.TotalAmountVnd,
		arg.PaidAmountVnd,
		arg.IsStockInwardAuto,
	)
	return err
}

const createPurchaseInvoiceLine = `-- name: CreatePurchaseInvoiceLine :exec
INSERT INTO purchase_invoice_lines (
    id,
    purchase_invoice_id,
    line_order,
    item_id,
    warehouse_id,
    debit_account_id,
    credit_account_id,
    quantity,
    unit_price_vnd,
    amount_vnd,
    vat_rate,
    vat_amount_vnd,
    note
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreatePurchaseInvoiceLineParams struct {
	ID                string         `json:"id"`
	PurchaseInvoiceID string         `json:"purchase_invoice_id"`
	LineOrder         int32          `json:"line_order"`
	ItemID            string         `json:"item_id"`
	WarehouseID       sql.NullString `json:"warehouse_id"`
	DebitAccountID    string         `json:"debit_account_id"`
	CreditAccountID   string         `json:"credit_account_id"`
	Quantity          string         `json:"quantity"`
	UnitPriceVnd      string         `json:"unit_price_vnd"`
	AmountVnd         string         `json:"amount_vnd"`
	VatRate           string         `json:"vat_rate"`
	VatAmountVnd      string         `json:"vat_amount_vnd"`
	Note              sql.NullString `json:"note"`
}

func (q *Queries) CreatePurchaseInvoiceLine(ctx context.Context, arg CreatePurchaseInvoiceLineParams) error {
	_, err := q.db.ExecContext(ctx, createPurchaseInvoiceLine,
		arg.ID,
		arg.PurchaseInvoiceID,
		arg.LineOrder,
		arg.ItemID,
		arg.WarehouseID,
		arg.DebitAccountID,
		arg.CreditAccountID,
		arg.Quantity,
		arg.UnitPriceVnd,
		arg.AmountVnd,
		arg.VatRate,
		arg.VatAmountVnd,
		arg.Note,
	)
	return err
}

const getPurchaseInvoiceByID = `-- name: GetPurchaseInvoiceByID :one
SELECT 
    id,
    voucher_id,
    company_profile_id,
    vendor_id,
    invoice_template,
    invoice_series,
    invoice_no,
    invoice_date,
    due_date,
    payment_status,
    subtotal_vnd,
    vat_amount_vnd,
    total_amount_vnd,
    paid_amount_vnd,
    is_stock_inward_auto
FROM purchase_invoices
WHERE id = ?
`

func (q *Queries) GetPurchaseInvoiceByID(ctx context.Context, id string) (PurchaseInvoice, error) {
	row := q.db.QueryRowContext(ctx, getPurchaseInvoiceByID, id)
	var i PurchaseInvoice
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.CompanyProfileID,
		&i.VendorID,
		&i.InvoiceTemplate,
		&i.InvoiceSeries,
		&i.InvoiceNo,
		&i.InvoiceDate,
		&i.DueDate,
		&i.PaymentStatus,
		&i.SubtotalVnd,
		&i.VatAmountVnd,
		&i.TotalAmountVnd,
		&i.PaidAmountVnd,
		&i.IsStockInwardAuto,
	)
	return i, err
}

const getPurchaseInvoiceByVoucherID = `-- name: GetPurchaseInvoiceByVoucherID :one
SELECT 
    id,
    voucher_id,
    company_profile_id,
    vendor_id,
    invoice_template,
    invoice_series,
    invoice_no,
    invoice_date,
    due_date,
    payment_status,
    subtotal_vnd,
    vat_amount_vnd,
    total_amount_vnd,
    paid_amount_vnd,
    is_stock_inward_auto
FROM purchase_invoices
WHERE voucher_id = ?
`

func (q *Queries) GetPurchaseInvoiceByVoucherID(ctx context.Context, voucherID string) (PurchaseInvoice, error) {
	row := q.db.QueryRowContext(ctx, getPurchaseInvoiceByVoucherID, voucherID)
	var i PurchaseInvoice
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.CompanyProfileID,
		&i.VendorID,
		&i.InvoiceTemplate,
		&i.InvoiceSeries,
		&i.InvoiceNo,
		&i.InvoiceDate,
		&i.DueDate,
		&i.PaymentStatus,
		&i.SubtotalVnd,
		&i.VatAmountVnd,
		&i.TotalAmountVnd,
		&i.PaidAmountVnd,
		&i.IsStockInwardAuto,
	)
	return i, err
}

const listPurchaseInvoiceLinesByInvoiceID = `-- name: ListPurchaseInvoiceLinesByInvoiceID :many
SELECT 
    id,
    purchase_invoice_id,
    line_order,
    item_id,
    warehouse_id,
    debit_account_id,
    credit_account_id,
    quantity,
    unit_price_vnd,
    amount_vnd,
    vat_rate,
    vat_amount_vnd,
    note
FROM purchase_invoice_lines
WHERE purchase_invoice_id = ?
ORDER BY line_order ASC
`

func (q *Queries) ListPurchaseInvoiceLinesByInvoiceID(ctx context.Context, purchaseInvoiceID string) ([]PurchaseInvoiceLine, error) {
	rows, err := q.db.QueryContext(ctx, listPurchaseInvoiceLinesByInvoiceID, purchaseInvoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseInvoiceLine
	for rows.Next() {
		var i PurchaseInvoiceLine
		if err := rows.Scan(
			&i.ID,
			&i.PurchaseInvoiceID,
			&i.LineOrder,
			&i.ItemID,
			&i.WarehouseID,
			&i.DebitAccountID,
			&i.CreditAccountID,
			&i.Quantity,
			&i.UnitPriceVnd,
			&i.AmountVnd,
			&i.VatRate,
			&i.VatAmountVnd,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePurchaseInvoicePaymentStatus = `-- name: UpdatePurchaseInvoicePaymentStatus :exec
UPDATE purchase_invoices
SET payment_status = ?, paid_amount_vnd = ?
WHERE id = ?
`

type UpdatePurchaseInvoicePaymentStatusParams struct {
	PaymentStatus PurchaseInvoicesPaymentStatus `json:"payment_status"`
	PaidAmountVnd string                        `json:"paid_amount_vnd"`
	ID            string                        `json:"id"`
}

func (q *Queries) UpdatePurchaseInvoicePaymentStatus(ctx context.Context, arg UpdatePurchaseInvoicePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePurchaseInvoicePaymentStatus, arg.PaymentStatus, arg.PaidAmountVnd, arg.ID)
	return err
}
