// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package mariadb

import (
	"context"
	"database/sql"
	"time"
)

const createSalesInvoice = `-- name: CreateSalesInvoice :exec
INSERT INTO sales_invoices (
    id,
    voucher_id,
    company_profile_id,
    customer_id,
    invoice_template,
    invoice_series,
    invoice_no,
    invoice_date,
    due_date,
    payment_method,
    einvoice_status,
    einvoice_code_cqt,
    subtotal_vnd,
    discount_vnd,
    vat_amount_vnd,
    total_amount_vnd,
    is_stock_outward_auto
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateSalesInvoiceParams struct {
	ID                 string                      `json:"id"`
	VoucherID          string                      `json:"voucher_id"`
	CompanyProfileID   string                      `json:"company_profile_id"`
	CustomerID         string                      `json:"customer_id"`
	InvoiceTemplate    string                      `json:"invoice_template"`
	InvoiceSeries      string                      `json:"invoice_series"`
	InvoiceNo          string                      `json:"invoice_no"`
	InvoiceDate        time.Time                   `json:"invoice_date"`
	DueDate            time.Time                   `json:"due_date"`
	PaymentMethod      string                      `json:"payment_method"`
	EinvoiceStatus     SalesInvoicesEinvoiceStatus `json:"einvoice_status"`
	EinvoiceCodeCqt    sql.NullString              `json:"einvoice_code_cqt"`
	SubtotalVnd        string                      `json:"subtotal_vnd"`
	DiscountVnd        string                      `json:"discount_vnd"`
	VatAmountVnd       string                      `json:"vat_amount_vnd"`
	TotalAmountVnd     string                      `json:"total_amount_vnd"`
	IsStockOutwardAuto bool                        `json:"is_stock_outward_auto"`
}

func (q *Queries) CreateSalesInvoice(ctx context.Context, arg CreateSalesInvoiceParams) error {
	_, err := q.db.ExecContext(ctx, createSalesInvoice,
		arg.ID,
		arg.VoucherID,
		arg.CompanyProfileID,
		arg.CustomerID,
		arg.InvoiceTemplate,
		arg.InvoiceSeries,
		arg.InvoiceNo,
		arg.InvoiceDate,
		arg.DueDate,
		arg.PaymentMethod,
		arg.EinvoiceStatus,
		arg.EinvoiceCodeCqt,
		arg.SubtotalVnd,
		arg.DiscountVnd,
		arg.VatAmountVnd,
		arg.TotalAmountVnd,
		arg.IsStockOutwardAuto,
	)
	return err
}

const createSalesInvoiceLine = `-- name: CreateSalesInvoiceLine :exec
INSERT INTO sales_invoice_lines (
    id,
    sales_invoice_id,
    line_order,
    item_id,
    warehouse_id,
    debit_account_id,
    credit_account_id,
    quantity,
    unit_price_vnd,
    amount_vnd,
    discount_rate,
    discount_amount_vnd,
    vat_rate,
    vat_amount_vnd,
    note
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateSalesInvoiceLineParams struct {
	ID                string         `json:"id"`
	SalesInvoiceID    string         `json:"sales_invoice_id"`
	LineOrder         int32          `json:"line_order"`
	ItemID            string         `json:"item_id"`
	WarehouseID       sql.NullString `json:"warehouse_id"`
	DebitAccountID    string         `json:"debit_account_id"`
	CreditAccountID   string         `json:"credit_account_id"`
	Quantity          string         `json:"quantity"`
	UnitPriceVnd      string         `json:"unit_price_vnd"`
	AmountVnd         string         `json:"amount_vnd"`
	DiscountRate      string         `json:"discount_rate"`
	DiscountAmountVnd string         `json:"discount_amount_vnd"`
	VatRate           string         `json:"vat_rate"`
	VatAmountVnd      string         `json:"vat_amount_vnd"`
	Note              sql.NullString `json:"note"`
}

func (q *Queries) CreateSalesInvoiceLine(ctx context.Context, arg CreateSalesInvoiceLineParams) error {
	_, err := q.db.ExecContext(ctx, createSalesInvoiceLine,
		arg.ID,
		arg.SalesInvoiceID,
		arg.LineOrder,
		arg.ItemID,
		arg.WarehouseID,
		arg.DebitAccountID,
		arg.CreditAccountID,
		arg.Quantity,
		arg.UnitPriceVnd,
		arg.AmountVnd,
		arg.DiscountRate,
		arg.DiscountAmountVnd,
		arg.VatRate,
		arg.VatAmountVnd,
		arg.Note,
	)
	return err
}

const getSalesInvoiceByID = `-- name: GetSalesInvoiceByID :one
SELECT 
    id,
    voucher_id,
    company_profile_id,
    customer_id,
    invoice_template,
    invoice_series,
    invoice_no,
    invoice_date,
    due_date,
    payment_method,
    einvoice_status,
    einvoice_code_cqt,
    subtotal_vnd,
    discount_vnd,
    vat_amount_vnd,
    total_amount_vnd,
    is_stock_outward_auto
FROM sales_invoices
WHERE id = ?
`

func (q *Queries) GetSalesInvoiceByID(ctx context.Context, id string) (SalesInvoice, error) {
	row := q.db.QueryRowContext(ctx, getSalesInvoiceByID, id)
	var i SalesInvoice
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.CompanyProfileID,
		&i.CustomerID,
		&i.InvoiceTemplate,
		&i.InvoiceSeries,
		&i.InvoiceNo,
		&i.InvoiceDate,
		&i.DueDate,
		&i.PaymentMethod,
		&i.EinvoiceStatus,
		&i.EinvoiceCodeCqt,
		&i.SubtotalVnd,
		&i.DiscountVnd,
		&i.VatAmountVnd,
		&i.TotalAmountVnd,
		&i.IsStockOutwardAuto,
	)
	return i, err
}

const getSalesInvoiceByVoucherID = `-- name: GetSalesInvoiceByVoucherID :one
SELECT 
    id,
    voucher_id,
    company_profile_id,
    customer_id,
    invoice_template,
    invoice_series,
    invoice_no,
    invoice_date,
    due_date,
    payment_method,
    einvoice_status,
    einvoice_code_cqt,
    subtotal_vnd,
    discount_vnd,
    vat_amount_vnd,
    total_amount_vnd,
    is_stock_outward_auto
FROM sales_invoices
WHERE voucher_id = ?
`

func (q *Queries) GetSalesInvoiceByVoucherID(ctx context.Context, voucherID string) (SalesInvoice, error) {
	row := q.db.QueryRowContext(ctx, getSalesInvoiceByVoucherID, voucherID)
	var i SalesInvoice
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.CompanyProfileID,
		&i.CustomerID,
		&i.InvoiceTemplate,
		&i.InvoiceSeries,
		&i.InvoiceNo,
		&i.InvoiceDate,
		&i.DueDate,
		&i.PaymentMethod,
		&i.EinvoiceStatus,
		&i.EinvoiceCodeCqt,
		&i.SubtotalVnd,
		&i.DiscountVnd,
		&i.VatAmountVnd,
		&i.TotalAmountVnd,
		&i.IsStockOutwardAuto,
	)
	return i, err
}

const listSalesInvoiceLinesByInvoiceID = `-- name: ListSalesInvoiceLinesByInvoiceID :many
SELECT 
    id,
    sales_invoice_id,
    line_order,
    item_id,
    warehouse_id,
    debit_account_id,
    credit_account_id,
    quantity,
    unit_price_vnd,
    amount_vnd,
    discount_rate,
    discount_amount_vnd,
    vat_rate,
    vat_amount_vnd,
    note
FROM sales_invoice_lines
WHERE sales_invoice_id = ?
ORDER BY line_order ASC
`

func (q *Queries) ListSalesInvoiceLinesByInvoiceID(ctx context.Context, salesInvoiceID string) ([]SalesInvoiceLine, error) {
	rows, err := q.db.QueryContext(ctx, listSalesInvoiceLinesByInvoiceID, salesInvoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesInvoiceLine
	for rows.Next() {
		var i SalesInvoiceLine
		if err := rows.Scan(
			&i.ID,
			&i.SalesInvoiceID,
			&i.LineOrder,
			&i.ItemID,
			&i.WarehouseID,
			&i.DebitAccountID,
			&i.CreditAccountID,
			&i.Quantity,
			&i.UnitPriceVnd,
			&i.AmountVnd,
			&i.DiscountRate,
			&i.DiscountAmountVnd,
			&i.VatRate,
			&i.VatAmountVnd,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSalesInvoiceEInvoiceStatus = `-- name: UpdateSalesInvoiceEInvoiceStatus :exec
UPDATE sales_invoices
SET einvoice_status = ?, einvoice_code_cqt = ?
WHERE id = ?
`

type UpdateSalesInvoiceEInvoiceStatusParams struct {
	EinvoiceStatus  SalesInvoicesEinvoiceStatus `json:"einvoice_status"`
	EinvoiceCodeCqt sql.NullString              `json:"einvoice_code_cqt"`
	ID              string                      `json:"id"`
}

func (q *Queries) UpdateSalesInvoiceEInvoiceStatus(ctx context.Context, arg UpdateSalesInvoiceEInvoiceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSalesInvoiceEInvoiceStatus, arg.EinvoiceStatus, arg.EinvoiceCodeCqt, arg.ID)
	return err
}
