// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spine.sql

package mariadb

import (
	"context"
	"database/sql"
	"time"
)

const getAccountByCode = `-- name: GetAccountByCode :one
SELECT id, company_profile_id, code, name, english_name, parent_id,
       account_level, nature, category, is_leaf, is_foreign_currency,
       requires_partner, requires_bank_account, requires_cost_center, requires_expense_item, is_active,
       created_at, updated_at
FROM accounts
WHERE company_profile_id = ? AND code = ?
LIMIT 1
`

type GetAccountByCodeParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	Code             string `json:"code"`
}

func (q *Queries) GetAccountByCode(ctx context.Context, arg GetAccountByCodeParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByCode, arg.CompanyProfileID, arg.Code)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Code,
		&i.Name,
		&i.EnglishName,
		&i.ParentID,
		&i.AccountLevel,
		&i.Nature,
		&i.Category,
		&i.IsLeaf,
		&i.IsForeignCurrency,
		&i.RequiresPartner,
		&i.RequiresBankAccount,
		&i.RequiresCostCenter,
		&i.RequiresExpenseItem,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, company_profile_id, code, name, english_name, parent_id,
       account_level, nature, category, is_leaf, is_foreign_currency,
       requires_partner, requires_bank_account, requires_cost_center, requires_expense_item, is_active,
       created_at, updated_at
FROM accounts
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAccountByID(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Code,
		&i.Name,
		&i.EnglishName,
		&i.ParentID,
		&i.AccountLevel,
		&i.Nature,
		&i.Category,
		&i.IsLeaf,
		&i.IsForeignCurrency,
		&i.RequiresPartner,
		&i.RequiresBankAccount,
		&i.RequiresCostCenter,
		&i.RequiresExpenseItem,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBaseCurrency = `-- name: GetBaseCurrency :one
SELECT code, company_profile_id, name, symbol, decimal_places, is_base, is_active, created_at, updated_at
FROM currencies
WHERE company_profile_id = ? AND is_base = TRUE
LIMIT 1
`

func (q *Queries) GetBaseCurrency(ctx context.Context, companyProfileID string) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getBaseCurrency, companyProfileID)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.CompanyProfileID,
		&i.Name,
		&i.Symbol,
		&i.DecimalPlaces,
		&i.IsBase,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCostCenterByCode = `-- name: GetCostCenterByCode :one
SELECT id, company_profile_id, branch_id, code, name, parent_id, is_leaf, is_active, created_at, updated_at
FROM cost_centers
WHERE company_profile_id = ? AND code = ?
LIMIT 1
`

type GetCostCenterByCodeParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	Code             string `json:"code"`
}

func (q *Queries) GetCostCenterByCode(ctx context.Context, arg GetCostCenterByCodeParams) (CostCenter, error) {
	row := q.db.QueryRowContext(ctx, getCostCenterByCode, arg.CompanyProfileID, arg.Code)
	var i CostCenter
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.BranchID,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.IsLeaf,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrencyByCode = `-- name: GetCurrencyByCode :one
SELECT code, company_profile_id, name, symbol, decimal_places, is_base, is_active, created_at, updated_at
FROM currencies
WHERE company_profile_id = ? AND code = ?
LIMIT 1
`

type GetCurrencyByCodeParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	Code             string `json:"code"`
}

func (q *Queries) GetCurrencyByCode(ctx context.Context, arg GetCurrencyByCodeParams) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getCurrencyByCode, arg.CompanyProfileID, arg.Code)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.CompanyProfileID,
		&i.Name,
		&i.Symbol,
		&i.DecimalPlaces,
		&i.IsBase,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEffectiveExchangeRate = `-- name: GetEffectiveExchangeRate :one
SELECT id, company_profile_id, currency_code, rate_date, rate_type, rate, source_bank, created_at, created_by
FROM exchange_rates
WHERE company_profile_id = ?
  AND currency_code = ?
  AND rate_type = ?
  AND rate_date <= ?
ORDER BY rate_date DESC
LIMIT 1
`

type GetEffectiveExchangeRateParams struct {
	CompanyProfileID string                `json:"company_profile_id"`
	CurrencyCode     string                `json:"currency_code"`
	RateType         ExchangeRatesRateType `json:"rate_type"`
	RateDate         time.Time             `json:"rate_date"`
}

func (q *Queries) GetEffectiveExchangeRate(ctx context.Context, arg GetEffectiveExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRowContext(ctx, getEffectiveExchangeRate,
		arg.CompanyProfileID,
		arg.CurrencyCode,
		arg.RateType,
		arg.RateDate,
	)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.CurrencyCode,
		&i.RateDate,
		&i.RateType,
		&i.Rate,
		&i.SourceBank,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getExpenseItemByCode = `-- name: GetExpenseItemByCode :one
SELECT id, company_profile_id, code, name, category, parent_id, is_leaf, is_active, created_at, updated_at
FROM expense_items
WHERE company_profile_id = ? AND code = ?
LIMIT 1
`

type GetExpenseItemByCodeParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	Code             string `json:"code"`
}

func (q *Queries) GetExpenseItemByCode(ctx context.Context, arg GetExpenseItemByCodeParams) (ExpenseItem, error) {
	row := q.db.QueryRowContext(ctx, getExpenseItemByCode, arg.CompanyProfileID, arg.Code)
	var i ExpenseItem
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Code,
		&i.Name,
		&i.Category,
		&i.ParentID,
		&i.IsLeaf,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFiscalYearByYear = `-- name: GetFiscalYearByYear :one
SELECT id, company_profile_id, year, start_date, end_date, status, created_at, updated_at
FROM fiscal_years
WHERE company_profile_id = ? AND year = ?
LIMIT 1
`

type GetFiscalYearByYearParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	Year             int32  `json:"year"`
}

func (q *Queries) GetFiscalYearByYear(ctx context.Context, arg GetFiscalYearByYearParams) (FiscalYear, error) {
	row := q.db.QueryRowContext(ctx, getFiscalYearByYear, arg.CompanyProfileID, arg.Year)
	var i FiscalYear
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Year,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPeriodByDate = `-- name: GetPeriodByDate :one
SELECT id, fiscal_year_id, company_profile_id, period_number, name,
       start_date, end_date, lock_date, status, created_at, updated_at
FROM accounting_periods
WHERE company_profile_id = ?
  AND start_date <= ?
  AND end_date >= ?
LIMIT 1
`

type GetPeriodByDateParams struct {
	CompanyProfileID string    `json:"company_profile_id"`
	StartDate        time.Time `json:"start_date"`
	EndDate          time.Time `json:"end_date"`
}

func (q *Queries) GetPeriodByDate(ctx context.Context, arg GetPeriodByDateParams) (AccountingPeriod, error) {
	row := q.db.QueryRowContext(ctx, getPeriodByDate, arg.CompanyProfileID, arg.StartDate, arg.EndDate)
	var i AccountingPeriod
	err := row.Scan(
		&i.ID,
		&i.FiscalYearID,
		&i.CompanyProfileID,
		&i.PeriodNumber,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.LockDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsByCompany = `-- name: ListAccountsByCompany :many
SELECT id, company_profile_id, code, name, english_name, parent_id,
       account_level, nature, category, is_leaf, is_foreign_currency,
       requires_partner, requires_bank_account, requires_cost_center, requires_expense_item, is_active,
       created_at, updated_at
FROM accounts
WHERE company_profile_id = ?
ORDER BY code ASC
`

func (q *Queries) ListAccountsByCompany(ctx context.Context, companyProfileID string) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByCompany, companyProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.Code,
			&i.Name,
			&i.EnglishName,
			&i.ParentID,
			&i.AccountLevel,
			&i.Nature,
			&i.Category,
			&i.IsLeaf,
			&i.IsForeignCurrency,
			&i.RequiresPartner,
			&i.RequiresBankAccount,
			&i.RequiresCostCenter,
			&i.RequiresExpenseItem,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildAccounts = `-- name: ListChildAccounts :many
SELECT id, company_profile_id, code, name, english_name, parent_id,
       account_level, nature, category, is_leaf, is_foreign_currency,
       requires_partner, requires_bank_account, requires_cost_center, requires_expense_item, is_active,
       created_at, updated_at
FROM accounts
WHERE parent_id = ?
ORDER BY code ASC
`

func (q *Queries) ListChildAccounts(ctx context.Context, parentID sql.NullString) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listChildAccounts, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.Code,
			&i.Name,
			&i.EnglishName,
			&i.ParentID,
			&i.AccountLevel,
			&i.Nature,
			&i.Category,
			&i.IsLeaf,
			&i.IsForeignCurrency,
			&i.RequiresPartner,
			&i.RequiresBankAccount,
			&i.RequiresCostCenter,
			&i.RequiresExpenseItem,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostCentersByCompany = `-- name: ListCostCentersByCompany :many
SELECT id, company_profile_id, branch_id, code, name, parent_id, is_leaf, is_active, created_at, updated_at
FROM cost_centers
WHERE company_profile_id = ?
ORDER BY code ASC
`

func (q *Queries) ListCostCentersByCompany(ctx context.Context, companyProfileID string) ([]CostCenter, error) {
	rows, err := q.db.QueryContext(ctx, listCostCentersByCompany, companyProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostCenter
	for rows.Next() {
		var i CostCenter
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.BranchID,
			&i.Code,
			&i.Name,
			&i.ParentID,
			&i.IsLeaf,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrenciesByCompany = `-- name: ListCurrenciesByCompany :many
SELECT code, company_profile_id, name, symbol, decimal_places, is_base, is_active, created_at, updated_at
FROM currencies
WHERE company_profile_id = ?
ORDER BY is_base DESC, code ASC
`

func (q *Queries) ListCurrenciesByCompany(ctx context.Context, companyProfileID string) ([]Currency, error) {
	rows, err := q.db.QueryContext(ctx, listCurrenciesByCompany, companyProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Currency
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.Code,
			&i.CompanyProfileID,
			&i.Name,
			&i.Symbol,
			&i.DecimalPlaces,
			&i.IsBase,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExchangeRatesByDate = `-- name: ListExchangeRatesByDate :many
SELECT id, company_profile_id, currency_code, rate_date, rate_type, rate, source_bank, created_at, created_by
FROM exchange_rates
WHERE company_profile_id = ? AND rate_date = ?
ORDER BY currency_code ASC, rate_type ASC
`

type ListExchangeRatesByDateParams struct {
	CompanyProfileID string    `json:"company_profile_id"`
	RateDate         time.Time `json:"rate_date"`
}

func (q *Queries) ListExchangeRatesByDate(ctx context.Context, arg ListExchangeRatesByDateParams) ([]ExchangeRate, error) {
	rows, err := q.db.QueryContext(ctx, listExchangeRatesByDate, arg.CompanyProfileID, arg.RateDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExchangeRate
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.CurrencyCode,
			&i.RateDate,
			&i.RateType,
			&i.Rate,
			&i.SourceBank,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseItemsByCompany = `-- name: ListExpenseItemsByCompany :many
SELECT id, company_profile_id, code, name, category, parent_id, is_leaf, is_active, created_at, updated_at
FROM expense_items
WHERE company_profile_id = ?
ORDER BY code ASC
`

func (q *Queries) ListExpenseItemsByCompany(ctx context.Context, companyProfileID string) ([]ExpenseItem, error) {
	rows, err := q.db.QueryContext(ctx, listExpenseItemsByCompany, companyProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseItem
	for rows.Next() {
		var i ExpenseItem
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.Code,
			&i.Name,
			&i.Category,
			&i.ParentID,
			&i.IsLeaf,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiscalYearsByCompany = `-- name: ListFiscalYearsByCompany :many
SELECT id, company_profile_id, year, start_date, end_date, status, created_at, updated_at
FROM fiscal_years
WHERE company_profile_id = ?
ORDER BY year DESC
`

func (q *Queries) ListFiscalYearsByCompany(ctx context.Context, companyProfileID string) ([]FiscalYear, error) {
	rows, err := q.db.QueryContext(ctx, listFiscalYearsByCompany, companyProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FiscalYear
	for rows.Next() {
		var i FiscalYear
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.Year,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriodsByFiscalYear = `-- name: ListPeriodsByFiscalYear :many
SELECT id, fiscal_year_id, company_profile_id, period_number, name,
       start_date, end_date, lock_date, status, created_at, updated_at
FROM accounting_periods
WHERE fiscal_year_id = ?
ORDER BY period_number ASC
`

func (q *Queries) ListPeriodsByFiscalYear(ctx context.Context, fiscalYearID string) ([]AccountingPeriod, error) {
	rows, err := q.db.QueryContext(ctx, listPeriodsByFiscalYear, fiscalYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountingPeriod
	for rows.Next() {
		var i AccountingPeriod
		if err := rows.Scan(
			&i.ID,
			&i.FiscalYearID,
			&i.CompanyProfileID,
			&i.PeriodNumber,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.LockDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountLeafStatus = `-- name: UpdateAccountLeafStatus :exec
UPDATE accounts
SET is_leaf = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateAccountLeafStatusParams struct {
	IsLeaf bool   `json:"is_leaf"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateAccountLeafStatus(ctx context.Context, arg UpdateAccountLeafStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountLeafStatus, arg.IsLeaf, arg.ID)
	return err
}

const updatePeriodLock = `-- name: UpdatePeriodLock :exec
UPDATE accounting_periods
SET lock_date = ?, status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdatePeriodLockParams struct {
	LockDate time.Time               `json:"lock_date"`
	Status   AccountingPeriodsStatus `json:"status"`
	ID       string                  `json:"id"`
}

func (q *Queries) UpdatePeriodLock(ctx context.Context, arg UpdatePeriodLockParams) error {
	_, err := q.db.ExecContext(ctx, updatePeriodLock, arg.LockDate, arg.Status, arg.ID)
	return err
}

const upsertAccount = `-- name: UpsertAccount :exec

INSERT INTO accounts (
    id, company_profile_id, code, name, english_name, parent_id,
    account_level, nature, category, is_leaf, is_foreign_currency,
    requires_partner, requires_bank_account, requires_cost_center, requires_expense_item, is_active
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?
) ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    english_name = VALUES(english_name),
    parent_id = VALUES(parent_id),
    account_level = VALUES(account_level),
    nature = VALUES(nature),
    category = VALUES(category),
    is_leaf = VALUES(is_leaf),
    is_foreign_currency = VALUES(is_foreign_currency),
    requires_partner = VALUES(requires_partner),
    requires_bank_account = VALUES(requires_bank_account),
    requires_cost_center = VALUES(requires_cost_center),
    requires_expense_item = VALUES(requires_expense_item),
    is_active = VALUES(is_active),
    updated_at = CURRENT_TIMESTAMP
`

type UpsertAccountParams struct {
	ID                  string           `json:"id"`
	CompanyProfileID    string           `json:"company_profile_id"`
	Code                string           `json:"code"`
	Name                string           `json:"name"`
	EnglishName         sql.NullString   `json:"english_name"`
	ParentID            sql.NullString   `json:"parent_id"`
	AccountLevel        int32            `json:"account_level"`
	Nature              AccountsNature   `json:"nature"`
	Category            AccountsCategory `json:"category"`
	IsLeaf              bool             `json:"is_leaf"`
	IsForeignCurrency   bool             `json:"is_foreign_currency"`
	RequiresPartner     bool             `json:"requires_partner"`
	RequiresBankAccount bool             `json:"requires_bank_account"`
	RequiresCostCenter  bool             `json:"requires_cost_center"`
	RequiresExpenseItem bool             `json:"requires_expense_item"`
	IsActive            bool             `json:"is_active"`
}

// Chart of Accounts Queries
func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, upsertAccount,
		arg.ID,
		arg.CompanyProfileID,
		arg.Code,
		arg.Name,
		arg.EnglishName,
		arg.ParentID,
		arg.AccountLevel,
		arg.Nature,
		arg.Category,
		arg.IsLeaf,
		arg.IsForeignCurrency,
		arg.RequiresPartner,
		arg.RequiresBankAccount,
		arg.RequiresCostCenter,
		arg.RequiresExpenseItem,
		arg.IsActive,
	)
	return err
}

const upsertAccountingPeriod = `-- name: UpsertAccountingPeriod :exec

INSERT INTO accounting_periods (
    id, fiscal_year_id, company_profile_id, period_number, name,
    start_date, end_date, lock_date, status
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?
) ON DUPLICATE KEY UPDATE
    lock_date = VALUES(lock_date),
    status = VALUES(status),
    updated_at = CURRENT_TIMESTAMP
`

type UpsertAccountingPeriodParams struct {
	ID               string                  `json:"id"`
	FiscalYearID     string                  `json:"fiscal_year_id"`
	CompanyProfileID string                  `json:"company_profile_id"`
	PeriodNumber     int32                   `json:"period_number"`
	Name             string                  `json:"name"`
	StartDate        time.Time               `json:"start_date"`
	EndDate          time.Time               `json:"end_date"`
	LockDate         time.Time               `json:"lock_date"`
	Status           AccountingPeriodsStatus `json:"status"`
}

// Accounting Periods Queries
func (q *Queries) UpsertAccountingPeriod(ctx context.Context, arg UpsertAccountingPeriodParams) error {
	_, err := q.db.ExecContext(ctx, upsertAccountingPeriod,
		arg.ID,
		arg.FiscalYearID,
		arg.CompanyProfileID,
		arg.PeriodNumber,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.LockDate,
		arg.Status,
	)
	return err
}

const upsertCostCenter = `-- name: UpsertCostCenter :exec

INSERT INTO cost_centers (
    id, company_profile_id, branch_id, code, name, parent_id, is_leaf, is_active
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
) ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    parent_id = VALUES(parent_id),
    is_leaf = VALUES(is_leaf),
    is_active = VALUES(is_active),
    updated_at = CURRENT_TIMESTAMP
`

type UpsertCostCenterParams struct {
	ID               string         `json:"id"`
	CompanyProfileID string         `json:"company_profile_id"`
	BranchID         sql.NullString `json:"branch_id"`
	Code             string         `json:"code"`
	Name             string         `json:"name"`
	ParentID         sql.NullString `json:"parent_id"`
	IsLeaf           bool           `json:"is_leaf"`
	IsActive         bool           `json:"is_active"`
}

// Cost Centers Queries
func (q *Queries) UpsertCostCenter(ctx context.Context, arg UpsertCostCenterParams) error {
	_, err := q.db.ExecContext(ctx, upsertCostCenter,
		arg.ID,
		arg.CompanyProfileID,
		arg.BranchID,
		arg.Code,
		arg.Name,
		arg.ParentID,
		arg.IsLeaf,
		arg.IsActive,
	)
	return err
}

const upsertCurrency = `-- name: UpsertCurrency :exec

INSERT INTO currencies (
    code, company_profile_id, name, symbol, decimal_places, is_base, is_active
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
) ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    symbol = VALUES(symbol),
    decimal_places = VALUES(decimal_places),
    is_base = VALUES(is_base),
    is_active = VALUES(is_active),
    updated_at = CURRENT_TIMESTAMP
`

type UpsertCurrencyParams struct {
	Code             string `json:"code"`
	CompanyProfileID string `json:"company_profile_id"`
	Name             string `json:"name"`
	Symbol           string `json:"symbol"`
	DecimalPlaces    int32  `json:"decimal_places"`
	IsBase           bool   `json:"is_base"`
	IsActive         bool   `json:"is_active"`
}

// Currency Queries
func (q *Queries) UpsertCurrency(ctx context.Context, arg UpsertCurrencyParams) error {
	_, err := q.db.ExecContext(ctx, upsertCurrency,
		arg.Code,
		arg.CompanyProfileID,
		arg.Name,
		arg.Symbol,
		arg.DecimalPlaces,
		arg.IsBase,
		arg.IsActive,
	)
	return err
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :exec

INSERT INTO exchange_rates (
    id, company_profile_id, currency_code, rate_date, rate_type, rate, source_bank, created_by
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
) ON DUPLICATE KEY UPDATE
    rate = VALUES(rate),
    source_bank = VALUES(source_bank)
`

type UpsertExchangeRateParams struct {
	ID               string                `json:"id"`
	CompanyProfileID string                `json:"company_profile_id"`
	CurrencyCode     string                `json:"currency_code"`
	RateDate         time.Time             `json:"rate_date"`
	RateType         ExchangeRatesRateType `json:"rate_type"`
	Rate             string                `json:"rate"`
	SourceBank       string                `json:"source_bank"`
	CreatedBy        string                `json:"created_by"`
}

// Exchange Rate Queries
func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error {
	_, err := q.db.ExecContext(ctx, upsertExchangeRate,
		arg.ID,
		arg.CompanyProfileID,
		arg.CurrencyCode,
		arg.RateDate,
		arg.RateType,
		arg.Rate,
		arg.SourceBank,
		arg.CreatedBy,
	)
	return err
}

const upsertExpenseItem = `-- name: UpsertExpenseItem :exec

INSERT INTO expense_items (
    id, company_profile_id, code, name, category, parent_id, is_leaf, is_active
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
) ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    category = VALUES(category),
    parent_id = VALUES(parent_id),
    is_leaf = VALUES(is_leaf),
    is_active = VALUES(is_active),
    updated_at = CURRENT_TIMESTAMP
`

type UpsertExpenseItemParams struct {
	ID               string         `json:"id"`
	CompanyProfileID string         `json:"company_profile_id"`
	Code             string         `json:"code"`
	Name             string         `json:"name"`
	Category         string         `json:"category"`
	ParentID         sql.NullString `json:"parent_id"`
	IsLeaf           bool           `json:"is_leaf"`
	IsActive         bool           `json:"is_active"`
}

// Expense Items Queries
func (q *Queries) UpsertExpenseItem(ctx context.Context, arg UpsertExpenseItemParams) error {
	_, err := q.db.ExecContext(ctx, upsertExpenseItem,
		arg.ID,
		arg.CompanyProfileID,
		arg.Code,
		arg.Name,
		arg.Category,
		arg.ParentID,
		arg.IsLeaf,
		arg.IsActive,
	)
	return err
}

const upsertFiscalYear = `-- name: UpsertFiscalYear :exec

INSERT INTO fiscal_years (
    id, company_profile_id, year, start_date, end_date, status
) VALUES (
    ?, ?, ?, ?, ?, ?
) ON DUPLICATE KEY UPDATE
    status = VALUES(status),
    updated_at = CURRENT_TIMESTAMP
`

type UpsertFiscalYearParams struct {
	ID               string            `json:"id"`
	CompanyProfileID string            `json:"company_profile_id"`
	Year             int32             `json:"year"`
	StartDate        time.Time         `json:"start_date"`
	EndDate          time.Time         `json:"end_date"`
	Status           FiscalYearsStatus `json:"status"`
}

// Fiscal Years Queries
func (q *Queries) UpsertFiscalYear(ctx context.Context, arg UpsertFiscalYearParams) error {
	_, err := q.db.ExecContext(ctx, upsertFiscalYear,
		arg.ID,
		arg.CompanyProfileID,
		arg.Year,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
	)
	return err
}
