// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_options.sql

package mariadb

import (
	"context"
	"database/sql"
	"time"
)

const getEffectiveSystemOption = `-- name: GetEffectiveSystemOption :one
SELECT id, company_profile_id, branch_id, category, option_key,
       option_value, data_type, default_value, scope_level,
       description, is_readonly, is_encrypted, created_at, updated_at, updated_by
FROM system_options
WHERE company_profile_id = ?
  AND option_key = ?
  AND (branch_id = ? OR branch_id IS NULL)
ORDER BY CASE WHEN branch_id = ? THEN 0 ELSE 1 END
LIMIT 1
`

type GetEffectiveSystemOptionParams struct {
	CompanyProfileID string         `json:"company_profile_id"`
	OptionKey        string         `json:"option_key"`
	BranchID         sql.NullString `json:"branch_id"`
}

type GetEffectiveSystemOptionRow struct {
	ID               string         `json:"id"`
	CompanyProfileID string         `json:"company_profile_id"`
	BranchID         sql.NullString `json:"branch_id"`
	Category         string         `json:"category"`
	OptionKey        string         `json:"option_key"`
	OptionValue      string         `json:"option_value"`
	DataType         string         `json:"data_type"`
	DefaultValue     string         `json:"default_value"`
	ScopeLevel       string         `json:"scope_level"`
	Description      sql.NullString `json:"description"`
	IsReadonly       bool           `json:"is_readonly"`
	IsEncrypted      bool           `json:"is_encrypted"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	UpdatedBy        sql.NullString `json:"updated_by"`
}

func (q *Queries) GetEffectiveSystemOption(ctx context.Context, arg GetEffectiveSystemOptionParams) (GetEffectiveSystemOptionRow, error) {
	row := q.db.QueryRowContext(ctx, getEffectiveSystemOption,
		arg.CompanyProfileID,
		arg.OptionKey,
		arg.BranchID,
		arg.BranchID,
	)
	var i GetEffectiveSystemOptionRow
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.BranchID,
		&i.Category,
		&i.OptionKey,
		&i.OptionValue,
		&i.DataType,
		&i.DefaultValue,
		&i.ScopeLevel,
		&i.Description,
		&i.IsReadonly,
		&i.IsEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getEffectiveVoucherNumberingConfig = `-- name: GetEffectiveVoucherNumberingConfig :one
SELECT id, company_profile_id, branch_id, voucher_type, prefix, pattern,
       reset_frequency, current_sequence, last_reset_date, created_at, updated_at
FROM voucher_numbering_configs
WHERE company_profile_id = ?
  AND voucher_type = ?
  AND (branch_id = ? OR branch_id IS NULL)
ORDER BY CASE WHEN branch_id = ? THEN 0 ELSE 1 END
LIMIT 1
`

type GetEffectiveVoucherNumberingConfigParams struct {
	CompanyProfileID string         `json:"company_profile_id"`
	VoucherType      string         `json:"voucher_type"`
	BranchID         sql.NullString `json:"branch_id"`
}

type GetEffectiveVoucherNumberingConfigRow struct {
	ID               string                                `json:"id"`
	CompanyProfileID string                                `json:"company_profile_id"`
	BranchID         sql.NullString                        `json:"branch_id"`
	VoucherType      string                                `json:"voucher_type"`
	Prefix           string                                `json:"prefix"`
	Pattern          string                                `json:"pattern"`
	ResetFrequency   VoucherNumberingConfigsResetFrequency `json:"reset_frequency"`
	CurrentSequence  int64                                 `json:"current_sequence"`
	LastResetDate    time.Time                             `json:"last_reset_date"`
	CreatedAt        time.Time                             `json:"created_at"`
	UpdatedAt        time.Time                             `json:"updated_at"`
}

func (q *Queries) GetEffectiveVoucherNumberingConfig(ctx context.Context, arg GetEffectiveVoucherNumberingConfigParams) (GetEffectiveVoucherNumberingConfigRow, error) {
	row := q.db.QueryRowContext(ctx, getEffectiveVoucherNumberingConfig,
		arg.CompanyProfileID,
		arg.VoucherType,
		arg.BranchID,
		arg.BranchID,
	)
	var i GetEffectiveVoucherNumberingConfigRow
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.BranchID,
		&i.VoucherType,
		&i.Prefix,
		&i.Pattern,
		&i.ResetFrequency,
		&i.CurrentSequence,
		&i.LastResetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEffectiveVoucherNumberingConfigForUpdate = `-- name: GetEffectiveVoucherNumberingConfigForUpdate :one
SELECT id, company_profile_id, branch_id, voucher_type, prefix, pattern,
       reset_frequency, current_sequence, last_reset_date, created_at, updated_at
FROM voucher_numbering_configs
WHERE company_profile_id = ?
  AND voucher_type = ?
  AND (branch_id = ? OR branch_id IS NULL)
ORDER BY CASE WHEN branch_id = ? THEN 0 ELSE 1 END
LIMIT 1
FOR UPDATE
`

type GetEffectiveVoucherNumberingConfigForUpdateParams struct {
	CompanyProfileID string         `json:"company_profile_id"`
	VoucherType      string         `json:"voucher_type"`
	BranchID         sql.NullString `json:"branch_id"`
}

type GetEffectiveVoucherNumberingConfigForUpdateRow struct {
	ID               string                                `json:"id"`
	CompanyProfileID string                                `json:"company_profile_id"`
	BranchID         sql.NullString                        `json:"branch_id"`
	VoucherType      string                                `json:"voucher_type"`
	Prefix           string                                `json:"prefix"`
	Pattern          string                                `json:"pattern"`
	ResetFrequency   VoucherNumberingConfigsResetFrequency `json:"reset_frequency"`
	CurrentSequence  int64                                 `json:"current_sequence"`
	LastResetDate    time.Time                             `json:"last_reset_date"`
	CreatedAt        time.Time                             `json:"created_at"`
	UpdatedAt        time.Time                             `json:"updated_at"`
}

func (q *Queries) GetEffectiveVoucherNumberingConfigForUpdate(ctx context.Context, arg GetEffectiveVoucherNumberingConfigForUpdateParams) (GetEffectiveVoucherNumberingConfigForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getEffectiveVoucherNumberingConfigForUpdate,
		arg.CompanyProfileID,
		arg.VoucherType,
		arg.BranchID,
		arg.BranchID,
	)
	var i GetEffectiveVoucherNumberingConfigForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.BranchID,
		&i.VoucherType,
		&i.Prefix,
		&i.Pattern,
		&i.ResetFrequency,
		&i.CurrentSequence,
		&i.LastResetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemOption = `-- name: GetSystemOption :one
SELECT id, company_profile_id, branch_id, category, option_key,
       option_value, data_type, default_value, scope_level,
       description, is_readonly, is_encrypted, created_at, updated_at, updated_by
FROM system_options
WHERE company_profile_id = ?
  AND ((branch_id IS NULL AND ? IS NULL) OR branch_id = ?)
  AND option_key = ?
LIMIT 1
`

type GetSystemOptionParams struct {
	CompanyProfileID string         `json:"company_profile_id"`
	BranchID         sql.NullString `json:"branch_id"`
	OptionKey        string         `json:"option_key"`
}

type GetSystemOptionRow struct {
	ID               string         `json:"id"`
	CompanyProfileID string         `json:"company_profile_id"`
	BranchID         sql.NullString `json:"branch_id"`
	Category         string         `json:"category"`
	OptionKey        string         `json:"option_key"`
	OptionValue      string         `json:"option_value"`
	DataType         string         `json:"data_type"`
	DefaultValue     string         `json:"default_value"`
	ScopeLevel       string         `json:"scope_level"`
	Description      sql.NullString `json:"description"`
	IsReadonly       bool           `json:"is_readonly"`
	IsEncrypted      bool           `json:"is_encrypted"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	UpdatedBy        sql.NullString `json:"updated_by"`
}

func (q *Queries) GetSystemOption(ctx context.Context, arg GetSystemOptionParams) (GetSystemOptionRow, error) {
	row := q.db.QueryRowContext(ctx, getSystemOption,
		arg.CompanyProfileID,
		arg.BranchID,
		arg.BranchID,
		arg.OptionKey,
	)
	var i GetSystemOptionRow
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.BranchID,
		&i.Category,
		&i.OptionKey,
		&i.OptionValue,
		&i.DataType,
		&i.DefaultValue,
		&i.ScopeLevel,
		&i.Description,
		&i.IsReadonly,
		&i.IsEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getVoucherNumberingConfigByID = `-- name: GetVoucherNumberingConfigByID :one
SELECT id, company_profile_id, branch_id, voucher_type, prefix, pattern,
       reset_frequency, current_sequence, last_reset_date, created_at, updated_at
FROM voucher_numbering_configs
WHERE id = ?
LIMIT 1
`

type GetVoucherNumberingConfigByIDRow struct {
	ID               string                                `json:"id"`
	CompanyProfileID string                                `json:"company_profile_id"`
	BranchID         sql.NullString                        `json:"branch_id"`
	VoucherType      string                                `json:"voucher_type"`
	Prefix           string                                `json:"prefix"`
	Pattern          string                                `json:"pattern"`
	ResetFrequency   VoucherNumberingConfigsResetFrequency `json:"reset_frequency"`
	CurrentSequence  int64                                 `json:"current_sequence"`
	LastResetDate    time.Time                             `json:"last_reset_date"`
	CreatedAt        time.Time                             `json:"created_at"`
	UpdatedAt        time.Time                             `json:"updated_at"`
}

func (q *Queries) GetVoucherNumberingConfigByID(ctx context.Context, id string) (GetVoucherNumberingConfigByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getVoucherNumberingConfigByID, id)
	var i GetVoucherNumberingConfigByIDRow
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.BranchID,
		&i.VoucherType,
		&i.Prefix,
		&i.Pattern,
		&i.ResetFrequency,
		&i.CurrentSequence,
		&i.LastResetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConfigHistory = `-- name: ListConfigHistory :many
SELECT id, company_profile_id, option_key, old_value, new_value,
       changed_by, changed_at, reason, client_ip
FROM system_config_history
WHERE company_profile_id = ? AND option_key = ?
ORDER BY changed_at DESC
LIMIT ?
`

type ListConfigHistoryParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	OptionKey        string `json:"option_key"`
	Limit            int32  `json:"limit"`
}

func (q *Queries) ListConfigHistory(ctx context.Context, arg ListConfigHistoryParams) ([]SystemConfigHistory, error) {
	rows, err := q.db.QueryContext(ctx, listConfigHistory, arg.CompanyProfileID, arg.OptionKey, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemConfigHistory
	for rows.Next() {
		var i SystemConfigHistory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.OptionKey,
			&i.OldValue,
			&i.NewValue,
			&i.ChangedBy,
			&i.ChangedAt,
			&i.Reason,
			&i.ClientIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemOptionsByCategory = `-- name: ListSystemOptionsByCategory :many
SELECT id, company_profile_id, branch_id, category, option_key,
       option_value, data_type, default_value, scope_level,
       description, is_readonly, is_encrypted, created_at, updated_at, updated_by
FROM system_options
WHERE company_profile_id = ? AND category = ?
ORDER BY option_key ASC
`

type ListSystemOptionsByCategoryParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	Category         string `json:"category"`
}

type ListSystemOptionsByCategoryRow struct {
	ID               string         `json:"id"`
	CompanyProfileID string         `json:"company_profile_id"`
	BranchID         sql.NullString `json:"branch_id"`
	Category         string         `json:"category"`
	OptionKey        string         `json:"option_key"`
	OptionValue      string         `json:"option_value"`
	DataType         string         `json:"data_type"`
	DefaultValue     string         `json:"default_value"`
	ScopeLevel       string         `json:"scope_level"`
	Description      sql.NullString `json:"description"`
	IsReadonly       bool           `json:"is_readonly"`
	IsEncrypted      bool           `json:"is_encrypted"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	UpdatedBy        sql.NullString `json:"updated_by"`
}

func (q *Queries) ListSystemOptionsByCategory(ctx context.Context, arg ListSystemOptionsByCategoryParams) ([]ListSystemOptionsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listSystemOptionsByCategory, arg.CompanyProfileID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSystemOptionsByCategoryRow
	for rows.Next() {
		var i ListSystemOptionsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.BranchID,
			&i.Category,
			&i.OptionKey,
			&i.OptionValue,
			&i.DataType,
			&i.DefaultValue,
			&i.ScopeLevel,
			&i.Description,
			&i.IsReadonly,
			&i.IsEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemOptionsByCompany = `-- name: ListSystemOptionsByCompany :many
SELECT id, company_profile_id, branch_id, category, option_key,
       option_value, data_type, default_value, scope_level,
       description, is_readonly, is_encrypted, created_at, updated_at, updated_by
FROM system_options
WHERE company_profile_id = ?
ORDER BY category ASC, option_key ASC
`

type ListSystemOptionsByCompanyRow struct {
	ID               string         `json:"id"`
	CompanyProfileID string         `json:"company_profile_id"`
	BranchID         sql.NullString `json:"branch_id"`
	Category         string         `json:"category"`
	OptionKey        string         `json:"option_key"`
	OptionValue      string         `json:"option_value"`
	DataType         string         `json:"data_type"`
	DefaultValue     string         `json:"default_value"`
	ScopeLevel       string         `json:"scope_level"`
	Description      sql.NullString `json:"description"`
	IsReadonly       bool           `json:"is_readonly"`
	IsEncrypted      bool           `json:"is_encrypted"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	UpdatedBy        sql.NullString `json:"updated_by"`
}

func (q *Queries) ListSystemOptionsByCompany(ctx context.Context, companyProfileID string) ([]ListSystemOptionsByCompanyRow, error) {
	rows, err := q.db.QueryContext(ctx, listSystemOptionsByCompany, companyProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSystemOptionsByCompanyRow
	for rows.Next() {
		var i ListSystemOptionsByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.BranchID,
			&i.Category,
			&i.OptionKey,
			&i.OptionValue,
			&i.DataType,
			&i.DefaultValue,
			&i.ScopeLevel,
			&i.Description,
			&i.IsReadonly,
			&i.IsEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoucherNumberingConfigs = `-- name: ListVoucherNumberingConfigs :many
SELECT id, company_profile_id, branch_id, voucher_type, prefix, pattern,
       reset_frequency, current_sequence, last_reset_date, created_at, updated_at
FROM voucher_numbering_configs
WHERE company_profile_id = ?
ORDER BY voucher_type ASC
`

type ListVoucherNumberingConfigsRow struct {
	ID               string                                `json:"id"`
	CompanyProfileID string                                `json:"company_profile_id"`
	BranchID         sql.NullString                        `json:"branch_id"`
	VoucherType      string                                `json:"voucher_type"`
	Prefix           string                                `json:"prefix"`
	Pattern          string                                `json:"pattern"`
	ResetFrequency   VoucherNumberingConfigsResetFrequency `json:"reset_frequency"`
	CurrentSequence  int64                                 `json:"current_sequence"`
	LastResetDate    time.Time                             `json:"last_reset_date"`
	CreatedAt        time.Time                             `json:"created_at"`
	UpdatedAt        time.Time                             `json:"updated_at"`
}

func (q *Queries) ListVoucherNumberingConfigs(ctx context.Context, companyProfileID string) ([]ListVoucherNumberingConfigsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVoucherNumberingConfigs, companyProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVoucherNumberingConfigsRow
	for rows.Next() {
		var i ListVoucherNumberingConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.BranchID,
			&i.VoucherType,
			&i.Prefix,
			&i.Pattern,
			&i.ResetFrequency,
			&i.CurrentSequence,
			&i.LastResetDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordConfigHistory = `-- name: RecordConfigHistory :exec
INSERT INTO system_config_history (
    id, company_profile_id, option_key, old_value, new_value, changed_by, reason, client_ip
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
`

type RecordConfigHistoryParams struct {
	ID               string         `json:"id"`
	CompanyProfileID string         `json:"company_profile_id"`
	OptionKey        string         `json:"option_key"`
	OldValue         sql.NullString `json:"old_value"`
	NewValue         string         `json:"new_value"`
	ChangedBy        string         `json:"changed_by"`
	Reason           sql.NullString `json:"reason"`
	ClientIp         sql.NullString `json:"client_ip"`
}

func (q *Queries) RecordConfigHistory(ctx context.Context, arg RecordConfigHistoryParams) error {
	_, err := q.db.ExecContext(ctx, recordConfigHistory,
		arg.ID,
		arg.CompanyProfileID,
		arg.OptionKey,
		arg.OldValue,
		arg.NewValue,
		arg.ChangedBy,
		arg.Reason,
		arg.ClientIp,
	)
	return err
}

const updateVoucherSequence = `-- name: UpdateVoucherSequence :exec
UPDATE voucher_numbering_configs
SET current_sequence = ?,
    last_reset_date = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateVoucherSequenceParams struct {
	CurrentSequence int64     `json:"current_sequence"`
	LastResetDate   time.Time `json:"last_reset_date"`
	ID              string    `json:"id"`
}

func (q *Queries) UpdateVoucherSequence(ctx context.Context, arg UpdateVoucherSequenceParams) error {
	_, err := q.db.ExecContext(ctx, updateVoucherSequence, arg.CurrentSequence, arg.LastResetDate, arg.ID)
	return err
}

const upsertSystemOption = `-- name: UpsertSystemOption :exec

INSERT INTO system_options (
    id, company_profile_id, branch_id, category, option_key,
    option_value, data_type, default_value, scope_level,
    description, is_readonly, is_encrypted, updated_by
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?
) ON DUPLICATE KEY UPDATE
    option_value = VALUES(option_value),
    updated_at = CURRENT_TIMESTAMP,
    updated_by = VALUES(updated_by)
`

type UpsertSystemOptionParams struct {
	ID               string         `json:"id"`
	CompanyProfileID string         `json:"company_profile_id"`
	BranchID         sql.NullString `json:"branch_id"`
	Category         string         `json:"category"`
	OptionKey        string         `json:"option_key"`
	OptionValue      string         `json:"option_value"`
	DataType         string         `json:"data_type"`
	DefaultValue     string         `json:"default_value"`
	ScopeLevel       string         `json:"scope_level"`
	Description      sql.NullString `json:"description"`
	IsReadonly       bool           `json:"is_readonly"`
	IsEncrypted      bool           `json:"is_encrypted"`
	UpdatedBy        sql.NullString `json:"updated_by"`
}

// System Options Queries
func (q *Queries) UpsertSystemOption(ctx context.Context, arg UpsertSystemOptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSystemOption,
		arg.ID,
		arg.CompanyProfileID,
		arg.BranchID,
		arg.Category,
		arg.OptionKey,
		arg.OptionValue,
		arg.DataType,
		arg.DefaultValue,
		arg.ScopeLevel,
		arg.Description,
		arg.IsReadonly,
		arg.IsEncrypted,
		arg.UpdatedBy,
	)
	return err
}

const upsertVoucherNumberingConfig = `-- name: UpsertVoucherNumberingConfig :exec

INSERT INTO voucher_numbering_configs (
    id, company_profile_id, branch_id, voucher_type,
    prefix, pattern, reset_frequency, current_sequence, last_reset_date
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, ?, ?
) ON DUPLICATE KEY UPDATE
    prefix = VALUES(prefix),
    pattern = VALUES(pattern),
    reset_frequency = VALUES(reset_frequency),
    current_sequence = VALUES(current_sequence),
    last_reset_date = VALUES(last_reset_date),
    updated_at = CURRENT_TIMESTAMP
`

type UpsertVoucherNumberingConfigParams struct {
	ID               string                                `json:"id"`
	CompanyProfileID string                                `json:"company_profile_id"`
	BranchID         sql.NullString                        `json:"branch_id"`
	VoucherType      string                                `json:"voucher_type"`
	Prefix           string                                `json:"prefix"`
	Pattern          string                                `json:"pattern"`
	ResetFrequency   VoucherNumberingConfigsResetFrequency `json:"reset_frequency"`
	CurrentSequence  int64                                 `json:"current_sequence"`
	LastResetDate    time.Time                             `json:"last_reset_date"`
}

// Voucher Numbering Queries
func (q *Queries) UpsertVoucherNumberingConfig(ctx context.Context, arg UpsertVoucherNumberingConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertVoucherNumberingConfig,
		arg.ID,
		arg.CompanyProfileID,
		arg.BranchID,
		arg.VoucherType,
		arg.Prefix,
		arg.Pattern,
		arg.ResetFrequency,
		arg.CurrentSequence,
		arg.LastResetDate,
	)
	return err
}
