// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package mariadb

import (
	"context"
	"database/sql"
	"encoding/json"
)

const getActiveCompanyProfile = `-- name: GetActiveCompanyProfile :one
SELECT id, tax_code, legal_name, trade_name, english_name, address, province_city, district_ward,
       phone, email, website, legal_representative, representative_position, chief_accountant,
       tax_authority_code, tax_authority_name, state_budget_chapter, regime, base_currency,
       fiscal_year_start_month, vat_method, costing_method, business_type, registered_banks,
       einvoice_config, is_active, lock_date, created_at, updated_at
FROM company_profile
WHERE is_active = TRUE
LIMIT 1
`

func (q *Queries) GetActiveCompanyProfile(ctx context.Context) (CompanyProfile, error) {
	row := q.db.QueryRowContext(ctx, getActiveCompanyProfile)
	var i CompanyProfile
	err := row.Scan(
		&i.ID,
		&i.TaxCode,
		&i.LegalName,
		&i.TradeName,
		&i.EnglishName,
		&i.Address,
		&i.ProvinceCity,
		&i.DistrictWard,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.LegalRepresentative,
		&i.RepresentativePosition,
		&i.ChiefAccountant,
		&i.TaxAuthorityCode,
		&i.TaxAuthorityName,
		&i.StateBudgetChapter,
		&i.Regime,
		&i.BaseCurrency,
		&i.FiscalYearStartMonth,
		&i.VatMethod,
		&i.CostingMethod,
		&i.BusinessType,
		&i.RegisteredBanks,
		&i.EinvoiceConfig,
		&i.IsActive,
		&i.LockDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyProfileByTaxCode = `-- name: GetCompanyProfileByTaxCode :one
SELECT id, tax_code, legal_name, trade_name, english_name, address, province_city, district_ward,
       phone, email, website, legal_representative, representative_position, chief_accountant,
       tax_authority_code, tax_authority_name, state_budget_chapter, regime, base_currency,
       fiscal_year_start_month, vat_method, costing_method, business_type, registered_banks,
       einvoice_config, is_active, lock_date, created_at, updated_at
FROM company_profile
WHERE tax_code = ?
LIMIT 1
`

func (q *Queries) GetCompanyProfileByTaxCode(ctx context.Context, taxCode string) (CompanyProfile, error) {
	row := q.db.QueryRowContext(ctx, getCompanyProfileByTaxCode, taxCode)
	var i CompanyProfile
	err := row.Scan(
		&i.ID,
		&i.TaxCode,
		&i.LegalName,
		&i.TradeName,
		&i.EnglishName,
		&i.Address,
		&i.ProvinceCity,
		&i.DistrictWard,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.LegalRepresentative,
		&i.RepresentativePosition,
		&i.ChiefAccountant,
		&i.TaxAuthorityCode,
		&i.TaxAuthorityName,
		&i.StateBudgetChapter,
		&i.Regime,
		&i.BaseCurrency,
		&i.FiscalYearStartMonth,
		&i.VatMethod,
		&i.CostingMethod,
		&i.BusinessType,
		&i.RegisteredBanks,
		&i.EinvoiceConfig,
		&i.IsActive,
		&i.LockDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLockDate = `-- name: UpdateLockDate :exec
UPDATE company_profile
SET lock_date = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateLockDateParams struct {
	LockDate sql.NullTime `json:"lock_date"`
	ID       string       `json:"id"`
}

func (q *Queries) UpdateLockDate(ctx context.Context, arg UpdateLockDateParams) error {
	_, err := q.db.ExecContext(ctx, updateLockDate, arg.LockDate, arg.ID)
	return err
}

const upsertCompanyProfile = `-- name: UpsertCompanyProfile :exec
INSERT INTO company_profile (
    id, tax_code, legal_name, trade_name, english_name, address, province_city, district_ward,
    phone, email, website, legal_representative, representative_position, chief_accountant,
    tax_authority_code, tax_authority_name, state_budget_chapter, regime, base_currency,
    fiscal_year_start_month, vat_method, costing_method, business_type, registered_banks,
    einvoice_config, is_active, lock_date
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?
) ON DUPLICATE KEY UPDATE
    legal_name = VALUES(legal_name),
    trade_name = VALUES(trade_name),
    english_name = VALUES(english_name),
    address = VALUES(address),
    province_city = VALUES(province_city),
    district_ward = VALUES(district_ward),
    phone = VALUES(phone),
    email = VALUES(email),
    website = VALUES(website),
    legal_representative = VALUES(legal_representative),
    representative_position = VALUES(representative_position),
    chief_accountant = VALUES(chief_accountant),
    tax_authority_code = VALUES(tax_authority_code),
    tax_authority_name = VALUES(tax_authority_name),
    state_budget_chapter = VALUES(state_budget_chapter),
    regime = VALUES(regime),
    vat_method = VALUES(vat_method),
    costing_method = VALUES(costing_method),
    business_type = VALUES(business_type),
    registered_banks = VALUES(registered_banks),
    einvoice_config = VALUES(einvoice_config),
    is_active = VALUES(is_active),
    lock_date = VALUES(lock_date)
`

type UpsertCompanyProfileParams struct {
	ID                     string                      `json:"id"`
	TaxCode                string                      `json:"tax_code"`
	LegalName              string                      `json:"legal_name"`
	TradeName              sql.NullString              `json:"trade_name"`
	EnglishName            sql.NullString              `json:"english_name"`
	Address                string                      `json:"address"`
	ProvinceCity           sql.NullString              `json:"province_city"`
	DistrictWard           sql.NullString              `json:"district_ward"`
	Phone                  sql.NullString              `json:"phone"`
	Email                  sql.NullString              `json:"email"`
	Website                sql.NullString              `json:"website"`
	LegalRepresentative    string                      `json:"legal_representative"`
	RepresentativePosition sql.NullString              `json:"representative_position"`
	ChiefAccountant        string                      `json:"chief_accountant"`
	TaxAuthorityCode       string                      `json:"tax_authority_code"`
	TaxAuthorityName       string                      `json:"tax_authority_name"`
	StateBudgetChapter     sql.NullString              `json:"state_budget_chapter"`
	Regime                 CompanyProfileRegime        `json:"regime"`
	BaseCurrency           string                      `json:"base_currency"`
	FiscalYearStartMonth   int8                        `json:"fiscal_year_start_month"`
	VatMethod              CompanyProfileVatMethod     `json:"vat_method"`
	CostingMethod          CompanyProfileCostingMethod `json:"costing_method"`
	BusinessType           CompanyProfileBusinessType  `json:"business_type"`
	RegisteredBanks        json.RawMessage             `json:"registered_banks"`
	EinvoiceConfig         json.RawMessage             `json:"einvoice_config"`
	IsActive               bool                        `json:"is_active"`
	LockDate               sql.NullTime                `json:"lock_date"`
}

func (q *Queries) UpsertCompanyProfile(ctx context.Context, arg UpsertCompanyProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertCompanyProfile,
		arg.ID,
		arg.TaxCode,
		arg.LegalName,
		arg.TradeName,
		arg.EnglishName,
		arg.Address,
		arg.ProvinceCity,
		arg.DistrictWard,
		arg.Phone,
		arg.Email,
		arg.Website,
		arg.LegalRepresentative,
		arg.RepresentativePosition,
		arg.ChiefAccountant,
		arg.TaxAuthorityCode,
		arg.TaxAuthorityName,
		arg.StateBudgetChapter,
		arg.Regime,
		arg.BaseCurrency,
		arg.FiscalYearStartMonth,
		arg.VatMethod,
		arg.CostingMethod,
		arg.BusinessType,
		arg.RegisteredBanks,
		arg.EinvoiceConfig,
		arg.IsActive,
		arg.LockDate,
	)
	return err
}
