// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package mariadb

import (
	"context"
	"database/sql"
	"time"
)

const assignUserOrgUnitScope = `-- name: AssignUserOrgUnitScope :exec
INSERT INTO user_org_unit_scopes (id, user_id, org_unit_id, is_default, include_children)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE is_default = VALUES(is_default), include_children = VALUES(include_children)
`

type AssignUserOrgUnitScopeParams struct {
	ID              string `json:"id"`
	UserID          string `json:"user_id"`
	OrgUnitID       string `json:"org_unit_id"`
	IsDefault       bool   `json:"is_default"`
	IncludeChildren bool   `json:"include_children"`
}

func (q *Queries) AssignUserOrgUnitScope(ctx context.Context, arg AssignUserOrgUnitScopeParams) error {
	_, err := q.db.ExecContext(ctx, assignUserOrgUnitScope,
		arg.ID,
		arg.UserID,
		arg.OrgUnitID,
		arg.IsDefault,
		arg.IncludeChildren,
	)
	return err
}

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO user_roles (user_id, role_id, assigned_by)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE assigned_at = CURRENT_TIMESTAMP
`

type AssignUserRoleParams struct {
	UserID     string         `json:"user_id"`
	RoleID     string         `json:"role_id"`
	AssignedBy sql.NullString `json:"assigned_by"`
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, assignUserRole, arg.UserID, arg.RoleID, arg.AssignedBy)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id, company_profile_id, username, email, password_hash, full_name,
    title, employee_code, status, failed_login_attempts, lockout_until,
    password_changed_at, must_change_password_next, mfa_secret, is_mfa_enabled,
    digital_cert_subject, digital_cert_serial
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?
)
`

type CreateUserParams struct {
	ID                     string         `json:"id"`
	CompanyProfileID       string         `json:"company_profile_id"`
	Username               string         `json:"username"`
	Email                  string         `json:"email"`
	PasswordHash           string         `json:"password_hash"`
	FullName               string         `json:"full_name"`
	Title                  sql.NullString `json:"title"`
	EmployeeCode           sql.NullString `json:"employee_code"`
	Status                 UsersStatus    `json:"status"`
	FailedLoginAttempts    int32          `json:"failed_login_attempts"`
	LockoutUntil           sql.NullTime   `json:"lockout_until"`
	PasswordChangedAt      time.Time      `json:"password_changed_at"`
	MustChangePasswordNext bool           `json:"must_change_password_next"`
	MfaSecret              sql.NullString `json:"mfa_secret"`
	IsMfaEnabled           bool           `json:"is_mfa_enabled"`
	DigitalCertSubject     sql.NullString `json:"digital_cert_subject"`
	DigitalCertSerial      sql.NullString `json:"digital_cert_serial"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.CompanyProfileID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Title,
		arg.EmployeeCode,
		arg.Status,
		arg.FailedLoginAttempts,
		arg.LockoutUntil,
		arg.PasswordChangedAt,
		arg.MustChangePasswordNext,
		arg.MfaSecret,
		arg.IsMfaEnabled,
		arg.DigitalCertSubject,
		arg.DigitalCertSerial,
	)
	return err
}

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, code, name, description, is_system, created_at, updated_at
FROM roles
WHERE code = ? LIMIT 1
`

func (q *Queries) GetRoleByCode(ctx context.Context, code string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByCode, code)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, company_profile_id, username, email, password_hash, full_name,
       title, employee_code, status, failed_login_attempts, lockout_until,
       password_changed_at, must_change_password_next, mfa_secret, is_mfa_enabled,
       digital_cert_subject, digital_cert_serial, last_login_at, last_login_ip,
       created_at, updated_at
FROM users
WHERE company_profile_id = ? AND email = ? LIMIT 1
`

type GetUserByEmailParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	Email            string `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, arg.CompanyProfileID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Title,
		&i.EmployeeCode,
		&i.Status,
		&i.FailedLoginAttempts,
		&i.LockoutUntil,
		&i.PasswordChangedAt,
		&i.MustChangePasswordNext,
		&i.MfaSecret,
		&i.IsMfaEnabled,
		&i.DigitalCertSubject,
		&i.DigitalCertSerial,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, company_profile_id, username, email, password_hash, full_name,
       title, employee_code, status, failed_login_attempts, lockout_until,
       password_changed_at, must_change_password_next, mfa_secret, is_mfa_enabled,
       digital_cert_subject, digital_cert_serial, last_login_at, last_login_ip,
       created_at, updated_at
FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Title,
		&i.EmployeeCode,
		&i.Status,
		&i.FailedLoginAttempts,
		&i.LockoutUntil,
		&i.PasswordChangedAt,
		&i.MustChangePasswordNext,
		&i.MfaSecret,
		&i.IsMfaEnabled,
		&i.DigitalCertSubject,
		&i.DigitalCertSerial,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, company_profile_id, username, email, password_hash, full_name,
       title, employee_code, status, failed_login_attempts, lockout_until,
       password_changed_at, must_change_password_next, mfa_secret, is_mfa_enabled,
       digital_cert_subject, digital_cert_serial, last_login_at, last_login_ip,
       created_at, updated_at
FROM users
WHERE company_profile_id = ? AND username = ? LIMIT 1
`

type GetUserByUsernameParams struct {
	CompanyProfileID string `json:"company_profile_id"`
	Username         string `json:"username"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, arg GetUserByUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, arg.CompanyProfileID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Title,
		&i.EmployeeCode,
		&i.Status,
		&i.FailedLoginAttempts,
		&i.LockoutUntil,
		&i.PasswordChangedAt,
		&i.MustChangePasswordNext,
		&i.MfaSecret,
		&i.IsMfaEnabled,
		&i.DigitalCertSubject,
		&i.DigitalCertSerial,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserOrgUnitScopes = `-- name: GetUserOrgUnitScopes :many
SELECT s.id, s.user_id, s.org_unit_id, s.is_default, s.include_children, s.created_at,
       b.code as branch_code, b.name as branch_name
FROM user_org_unit_scopes s
JOIN branch_org_units b ON s.org_unit_id = b.id
WHERE s.user_id = ?
ORDER BY s.is_default DESC, b.code ASC
`

type GetUserOrgUnitScopesRow struct {
	ID              string    `json:"id"`
	UserID          string    `json:"user_id"`
	OrgUnitID       string    `json:"org_unit_id"`
	IsDefault       bool      `json:"is_default"`
	IncludeChildren bool      `json:"include_children"`
	CreatedAt       time.Time `json:"created_at"`
	BranchCode      string    `json:"branch_code"`
	BranchName      string    `json:"branch_name"`
}

func (q *Queries) GetUserOrgUnitScopes(ctx context.Context, userID string) ([]GetUserOrgUnitScopesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserOrgUnitScopes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserOrgUnitScopesRow
	for rows.Next() {
		var i GetUserOrgUnitScopesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgUnitID,
			&i.IsDefault,
			&i.IncludeChildren,
			&i.CreatedAt,
			&i.BranchCode,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.code, r.name, r.description, r.is_system, r.created_at, r.updated_at
FROM roles r
JOIN user_roles ur ON r.id = ur.role_id
WHERE ur.user_id = ?
ORDER BY r.code
`

func (q *Queries) GetUserRoles(ctx context.Context, userID string) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, code, name, description, is_system, created_at, updated_at
FROM roles
ORDER BY code
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSoDConflictRules = `-- name: ListSoDConflictRules :many
SELECT id, role_code_a, role_code_b, legal_basis, description
FROM sod_conflict_rules
ORDER BY role_code_a, role_code_b
`

func (q *Queries) ListSoDConflictRules(ctx context.Context) ([]SodConflictRule, error) {
	rows, err := q.db.QueryContext(ctx, listSoDConflictRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SodConflictRule
	for rows.Next() {
		var i SodConflictRule
		if err := rows.Scan(
			&i.ID,
			&i.RoleCodeA,
			&i.RoleCodeB,
			&i.LegalBasis,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByCompany = `-- name: ListUsersByCompany :many
SELECT id, company_profile_id, username, email, password_hash, full_name,
       title, employee_code, status, failed_login_attempts, lockout_until,
       password_changed_at, must_change_password_next, mfa_secret, is_mfa_enabled,
       digital_cert_subject, digital_cert_serial, last_login_at, last_login_ip,
       created_at, updated_at
FROM users
WHERE company_profile_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListUsersByCompany(ctx context.Context, companyProfileID string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByCompany, companyProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Title,
			&i.EmployeeCode,
			&i.Status,
			&i.FailedLoginAttempts,
			&i.LockoutUntil,
			&i.PasswordChangedAt,
			&i.MustChangePasswordNext,
			&i.MfaSecret,
			&i.IsMfaEnabled,
			&i.DigitalCertSubject,
			&i.DigitalCertSerial,
			&i.LastLoginAt,
			&i.LastLoginIp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserOrgUnitScope = `-- name: RemoveUserOrgUnitScope :exec
DELETE FROM user_org_unit_scopes
WHERE user_id = ? AND org_unit_id = ?
`

type RemoveUserOrgUnitScopeParams struct {
	UserID    string `json:"user_id"`
	OrgUnitID string `json:"org_unit_id"`
}

func (q *Queries) RemoveUserOrgUnitScope(ctx context.Context, arg RemoveUserOrgUnitScopeParams) error {
	_, err := q.db.ExecContext(ctx, removeUserOrgUnitScope, arg.UserID, arg.OrgUnitID)
	return err
}

const removeUserRole = `-- name: RemoveUserRole :exec
DELETE FROM user_roles
WHERE user_id = ? AND role_id = ?
`

type RemoveUserRoleParams struct {
	UserID string `json:"user_id"`
	RoleID string `json:"role_id"`
}

func (q *Queries) RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, removeUserRole, arg.UserID, arg.RoleID)
	return err
}

const updateUserFailedLogin = `-- name: UpdateUserFailedLogin :exec
UPDATE users
SET failed_login_attempts = ?, status = ?, lockout_until = ?
WHERE id = ?
`

type UpdateUserFailedLoginParams struct {
	FailedLoginAttempts int32        `json:"failed_login_attempts"`
	Status              UsersStatus  `json:"status"`
	LockoutUntil        sql.NullTime `json:"lockout_until"`
	ID                  string       `json:"id"`
}

func (q *Queries) UpdateUserFailedLogin(ctx context.Context, arg UpdateUserFailedLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateUserFailedLogin,
		arg.FailedLoginAttempts,
		arg.Status,
		arg.LockoutUntil,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = ?, password_changed_at = ?, must_change_password_next = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash           string    `json:"password_hash"`
	PasswordChangedAt      time.Time `json:"password_changed_at"`
	MustChangePasswordNext bool      `json:"must_change_password_next"`
	ID                     string    `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword,
		arg.PasswordHash,
		arg.PasswordChangedAt,
		arg.MustChangePasswordNext,
		arg.ID,
	)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET status = ?, lockout_until = ?, failed_login_attempts = ?
WHERE id = ?
`

type UpdateUserStatusParams struct {
	Status              UsersStatus  `json:"status"`
	LockoutUntil        sql.NullTime `json:"lockout_until"`
	FailedLoginAttempts int32        `json:"failed_login_attempts"`
	ID                  string       `json:"id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus,
		arg.Status,
		arg.LockoutUntil,
		arg.FailedLoginAttempts,
		arg.ID,
	)
	return err
}

const updateUserSuccessfulLogin = `-- name: UpdateUserSuccessfulLogin :exec
UPDATE users
SET failed_login_attempts = 0, lockout_until = NULL, status = 'ACTIVE',
    last_login_at = ?, last_login_ip = ?
WHERE id = ?
`

type UpdateUserSuccessfulLoginParams struct {
	LastLoginAt sql.NullTime   `json:"last_login_at"`
	LastLoginIp sql.NullString `json:"last_login_ip"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateUserSuccessfulLogin(ctx context.Context, arg UpdateUserSuccessfulLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSuccessfulLogin, arg.LastLoginAt, arg.LastLoginIp, arg.ID)
	return err
}
