// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vouchers.sql

package mariadb

import (
	"context"
	"database/sql"
	"time"
)

const createVoucher = `-- name: CreateVoucher :exec
INSERT INTO vouchers (
    id, company_profile_id, branch_id, voucher_no, voucher_date, posted_date,
    voucher_type, description, status, total_debit, total_credit,
    currency_code, exchange_rate, source_document_id, source_document_type,
    idempotency_key, created_by, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?
)
`

type CreateVoucherParams struct {
	ID                 string              `json:"id"`
	CompanyProfileID   string              `json:"company_profile_id"`
	BranchID           sql.NullString      `json:"branch_id"`
	VoucherNo          string              `json:"voucher_no"`
	VoucherDate        time.Time           `json:"voucher_date"`
	PostedDate         time.Time           `json:"posted_date"`
	VoucherType        VouchersVoucherType `json:"voucher_type"`
	Description        string              `json:"description"`
	Status             VouchersStatus      `json:"status"`
	TotalDebit         string              `json:"total_debit"`
	TotalCredit        string              `json:"total_credit"`
	CurrencyCode       string              `json:"currency_code"`
	ExchangeRate       string              `json:"exchange_rate"`
	SourceDocumentID   sql.NullString      `json:"source_document_id"`
	SourceDocumentType sql.NullString      `json:"source_document_type"`
	IdempotencyKey     sql.NullString      `json:"idempotency_key"`
	CreatedBy          string              `json:"created_by"`
	CreatedAt          time.Time           `json:"created_at"`
	UpdatedAt          time.Time           `json:"updated_at"`
}

func (q *Queries) CreateVoucher(ctx context.Context, arg CreateVoucherParams) error {
	_, err := q.db.ExecContext(ctx, createVoucher,
		arg.ID,
		arg.CompanyProfileID,
		arg.BranchID,
		arg.VoucherNo,
		arg.VoucherDate,
		arg.PostedDate,
		arg.VoucherType,
		arg.Description,
		arg.Status,
		arg.TotalDebit,
		arg.TotalCredit,
		arg.CurrencyCode,
		arg.ExchangeRate,
		arg.SourceDocumentID,
		arg.SourceDocumentType,
		arg.IdempotencyKey,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteVoucherLinesByVoucherID = `-- name: DeleteVoucherLinesByVoucherID :exec
DELETE FROM voucher_lines
WHERE voucher_id = ?
`

func (q *Queries) DeleteVoucherLinesByVoucherID(ctx context.Context, voucherID string) error {
	_, err := q.db.ExecContext(ctx, deleteVoucherLinesByVoucherID, voucherID)
	return err
}

const getVoucherByID = `-- name: GetVoucherByID :one
SELECT id, company_profile_id, branch_id, voucher_no, voucher_date, posted_date,
       voucher_type, description, status, total_debit, total_credit,
       currency_code, exchange_rate, source_document_id, source_document_type,
       idempotency_key, created_by, created_at, updated_at
FROM vouchers
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetVoucherByID(ctx context.Context, id string) (Voucher, error) {
	row := q.db.QueryRowContext(ctx, getVoucherByID, id)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.BranchID,
		&i.VoucherNo,
		&i.VoucherDate,
		&i.PostedDate,
		&i.VoucherType,
		&i.Description,
		&i.Status,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.CurrencyCode,
		&i.ExchangeRate,
		&i.SourceDocumentID,
		&i.SourceDocumentType,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoucherByIdempotencyKey = `-- name: GetVoucherByIdempotencyKey :one
SELECT id, company_profile_id, branch_id, voucher_no, voucher_date, posted_date,
       voucher_type, description, status, total_debit, total_credit,
       currency_code, exchange_rate, source_document_id, source_document_type,
       idempotency_key, created_by, created_at, updated_at
FROM vouchers
WHERE company_profile_id = ? AND idempotency_key = ?
LIMIT 1
`

type GetVoucherByIdempotencyKeyParams struct {
	CompanyProfileID string         `json:"company_profile_id"`
	IdempotencyKey   sql.NullString `json:"idempotency_key"`
}

func (q *Queries) GetVoucherByIdempotencyKey(ctx context.Context, arg GetVoucherByIdempotencyKeyParams) (Voucher, error) {
	row := q.db.QueryRowContext(ctx, getVoucherByIdempotencyKey, arg.CompanyProfileID, arg.IdempotencyKey)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.BranchID,
		&i.VoucherNo,
		&i.VoucherDate,
		&i.PostedDate,
		&i.VoucherType,
		&i.Description,
		&i.Status,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.CurrencyCode,
		&i.ExchangeRate,
		&i.SourceDocumentID,
		&i.SourceDocumentType,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoucherByNo = `-- name: GetVoucherByNo :one
SELECT id, company_profile_id, branch_id, voucher_no, voucher_date, posted_date,
       voucher_type, description, status, total_debit, total_credit,
       currency_code, exchange_rate, source_document_id, source_document_type,
       idempotency_key, created_by, created_at, updated_at
FROM vouchers
WHERE company_profile_id = ? AND voucher_type = ? AND voucher_no = ?
LIMIT 1
`

type GetVoucherByNoParams struct {
	CompanyProfileID string              `json:"company_profile_id"`
	VoucherType      VouchersVoucherType `json:"voucher_type"`
	VoucherNo        string              `json:"voucher_no"`
}

func (q *Queries) GetVoucherByNo(ctx context.Context, arg GetVoucherByNoParams) (Voucher, error) {
	row := q.db.QueryRowContext(ctx, getVoucherByNo, arg.CompanyProfileID, arg.VoucherType, arg.VoucherNo)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.CompanyProfileID,
		&i.BranchID,
		&i.VoucherNo,
		&i.VoucherDate,
		&i.PostedDate,
		&i.VoucherType,
		&i.Description,
		&i.Status,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.CurrencyCode,
		&i.ExchangeRate,
		&i.SourceDocumentID,
		&i.SourceDocumentType,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVoucherLine = `-- name: InsertVoucherLine :exec
INSERT INTO voucher_lines (
    id, voucher_id, line_order, debit_account_id, credit_account_id,
    debit_account_code, credit_account_code, amount_fc, amount_vnd, note,
    customer_id, vendor_id, employee_id, item_id, warehouse_id,
    cost_center_id, expense_item_id, invoice_no, invoice_date, created_at
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?
)
`

type InsertVoucherLineParams struct {
	ID                string         `json:"id"`
	VoucherID         string         `json:"voucher_id"`
	LineOrder         int32          `json:"line_order"`
	DebitAccountID    string         `json:"debit_account_id"`
	CreditAccountID   string         `json:"credit_account_id"`
	DebitAccountCode  string         `json:"debit_account_code"`
	CreditAccountCode string         `json:"credit_account_code"`
	AmountFc          string         `json:"amount_fc"`
	AmountVnd         string         `json:"amount_vnd"`
	Note              sql.NullString `json:"note"`
	CustomerID        sql.NullString `json:"customer_id"`
	VendorID          sql.NullString `json:"vendor_id"`
	EmployeeID        sql.NullString `json:"employee_id"`
	ItemID            sql.NullString `json:"item_id"`
	WarehouseID       sql.NullString `json:"warehouse_id"`
	CostCenterID      sql.NullString `json:"cost_center_id"`
	ExpenseItemID     sql.NullString `json:"expense_item_id"`
	InvoiceNo         sql.NullString `json:"invoice_no"`
	InvoiceDate       sql.NullTime   `json:"invoice_date"`
	CreatedAt         time.Time      `json:"created_at"`
}

func (q *Queries) InsertVoucherLine(ctx context.Context, arg InsertVoucherLineParams) error {
	_, err := q.db.ExecContext(ctx, insertVoucherLine,
		arg.ID,
		arg.VoucherID,
		arg.LineOrder,
		arg.DebitAccountID,
		arg.CreditAccountID,
		arg.DebitAccountCode,
		arg.CreditAccountCode,
		arg.AmountFc,
		arg.AmountVnd,
		arg.Note,
		arg.CustomerID,
		arg.VendorID,
		arg.EmployeeID,
		arg.ItemID,
		arg.WarehouseID,
		arg.CostCenterID,
		arg.ExpenseItemID,
		arg.InvoiceNo,
		arg.InvoiceDate,
		arg.CreatedAt,
	)
	return err
}

const listVoucherLinesByVoucherID = `-- name: ListVoucherLinesByVoucherID :many
SELECT id, voucher_id, line_order, debit_account_id, credit_account_id,
       debit_account_code, credit_account_code, amount_fc, amount_vnd, note,
       customer_id, vendor_id, employee_id, item_id, warehouse_id,
       cost_center_id, expense_item_id, invoice_no, invoice_date, created_at
FROM voucher_lines
WHERE voucher_id = ?
ORDER BY line_order ASC
`

func (q *Queries) ListVoucherLinesByVoucherID(ctx context.Context, voucherID string) ([]VoucherLine, error) {
	rows, err := q.db.QueryContext(ctx, listVoucherLinesByVoucherID, voucherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoucherLine
	for rows.Next() {
		var i VoucherLine
		if err := rows.Scan(
			&i.ID,
			&i.VoucherID,
			&i.LineOrder,
			&i.DebitAccountID,
			&i.CreditAccountID,
			&i.DebitAccountCode,
			&i.CreditAccountCode,
			&i.AmountFc,
			&i.AmountVnd,
			&i.Note,
			&i.CustomerID,
			&i.VendorID,
			&i.EmployeeID,
			&i.ItemID,
			&i.WarehouseID,
			&i.CostCenterID,
			&i.ExpenseItemID,
			&i.InvoiceNo,
			&i.InvoiceDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVouchersByPeriod = `-- name: ListVouchersByPeriod :many
SELECT id, company_profile_id, branch_id, voucher_no, voucher_date, posted_date,
       voucher_type, description, status, total_debit, total_credit,
       currency_code, exchange_rate, source_document_id, source_document_type,
       idempotency_key, created_by, created_at, updated_at
FROM vouchers
WHERE company_profile_id = ? AND voucher_date >= ? AND voucher_date <= ?
ORDER BY voucher_date ASC, voucher_no ASC
`

type ListVouchersByPeriodParams struct {
	CompanyProfileID string    `json:"company_profile_id"`
	VoucherDate      time.Time `json:"voucher_date"`
	VoucherDate_2    time.Time `json:"voucher_date_2"`
}

func (q *Queries) ListVouchersByPeriod(ctx context.Context, arg ListVouchersByPeriodParams) ([]Voucher, error) {
	rows, err := q.db.QueryContext(ctx, listVouchersByPeriod, arg.CompanyProfileID, arg.VoucherDate, arg.VoucherDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Voucher
	for rows.Next() {
		var i Voucher
		if err := rows.Scan(
			&i.ID,
			&i.CompanyProfileID,
			&i.BranchID,
			&i.VoucherNo,
			&i.VoucherDate,
			&i.PostedDate,
			&i.VoucherType,
			&i.Description,
			&i.Status,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.CurrencyCode,
			&i.ExchangeRate,
			&i.SourceDocumentID,
			&i.SourceDocumentType,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVoucherStatus = `-- name: UpdateVoucherStatus :exec
UPDATE vouchers
SET status = ?, updated_at = ?
WHERE id = ?
`

type UpdateVoucherStatusParams struct {
	Status    VouchersStatus `json:"status"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateVoucherStatus(ctx context.Context, arg UpdateVoucherStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateVoucherStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const updateVoucherTotals = `-- name: UpdateVoucherTotals :exec
UPDATE vouchers
SET total_debit = ?, total_credit = ?, updated_at = ?
WHERE id = ?
`

type UpdateVoucherTotalsParams struct {
	TotalDebit  string    `json:"total_debit"`
	TotalCredit string    `json:"total_credit"`
	UpdatedAt   time.Time `json:"updated_at"`
	ID          string    `json:"id"`
}

func (q *Queries) UpdateVoucherTotals(ctx context.Context, arg UpdateVoucherTotalsParams) error {
	_, err := q.db.ExecContext(ctx, updateVoucherTotals,
		arg.TotalDebit,
		arg.TotalCredit,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
